#INCLUDE "PROTHEUS.CH"
#INCLUDE "APWEBSRV.CH"

/* ===============================================================================
WSDL Location    http://10.100.0.5:8091/ws/PORTALLICENCIADO.apw?WSDL
Gerado em        05/15/15 15:11:35
Observações      Código-Fonte gerado por ADVPL WSDL Client 1.120703
                 Alterações neste arquivo podem causar funcionamento incorreto
                 e serão perdidas caso o código-fonte seja gerado novamente.
=============================================================================== */

User Function _ZQKPRIM ; Return  // "dummy" function - Internal Use 

/* -------------------------------------------------------------------------------
WSDL Service WSPORTALLICENCIADO
------------------------------------------------------------------------------- */

WSCLIENT WSPORTALLICENCIADO

	WSMETHOD NEW
	WSMETHOD INIT
	WSMETHOD RESET
	WSMETHOD CLONE
	WSMETHOD GETATUALIZATIQUETA
	WSMETHOD GETATUALIZAVENDAS
	WSMETHOD GETESQUECISENHA
	WSMETHOD GETIMPRIMIBOLETO
	WSMETHOD GETLISTACONTRATOS
	WSMETHOD GETLISTAETIQUETAS
	WSMETHOD GETLISTALANCAVENDA
	WSMETHOD GETLISTAPRODUTOS
	WSMETHOD GETLOGINPORTALSCI
	WSMETHOD GETSALVAPRODUTOS
	WSMETHOD GETVISUALIZALANC

	WSDATA   _URL                      AS String
	WSDATA   _HEADOUT                  AS Array of String
	WSDATA   _COOKIES                  AS Array of String
	WSDATA   cCWEMPRESA                AS string
	WSDATA   cCWFILIAL                 AS string
	WSDATA   cCWSUSUARIO               AS string
	WSDATA   cCWSSENHA                 AS string
	WSDATA   cCCNPJ                    AS string
	WSDATA   cCCHVPORTAL               AS string
	WSDATA   cCTIPOLOGIN               AS string
	WSDATA   cCTIPOOPER                AS string
	WSDATA   cCDTENTREGA               AS string
	WSDATA   cCQUANTETIQ               AS string
	WSDATA   cCCNPJCLIENTE             AS string
	WSDATA   oWSGETATUALIZATIQUETARESULT AS PORTALLICENCIADO_RETATUALIZAETIQUETA
	WSDATA   cCZ9_NUMCTO               AS string
	WSDATA   cCZ9_REVCTO               AS string
	WSDATA   cCZ9_CODCLI               AS string
	WSDATA   cCZ9_LOJCLI               AS string
	WSDATA   cCZ9_PERIODO              AS string
	WSDATA   cCZ9_DTINIPE              AS string
	WSDATA   cCZ9_DTFIMPE              AS string
	WSDATA   cCZ9_VALOR                AS string
	WSDATA   cCZ9_CGC                  AS string
	WSDATA   cCZ9_VLRLIQ               AS string
	WSDATA   cCZ9_QUANT                AS string
	WSDATA   oWSGETATUALIZAVENDASRESULT AS PORTALLICENCIADO_RETATUALIZAVENDAS
	WSDATA   oWSGETESQUECISENHARESULT  AS PORTALLICENCIADO_RETESQUECISENHA
	WSDATA   cCZ9_PREFIXO              AS string
	WSDATA   cCZ9_NUM                  AS string
	WSDATA   cCZ9_PARCELA              AS string
	WSDATA   cCZ9_TIPO                 AS string
	WSDATA   cCZ9_CLIENTE              AS string
	WSDATA   cCZ9_LOJA                 AS string
	WSDATA   oWSGETIMPRIMIBOLETORESULT AS PORTALLICENCIADO_RETIMPRIMIBOLETO
	WSDATA   oWSGETLISTACONTRATOSRESULT AS PORTALLICENCIADO_RETLISTACONTRATOS
	WSDATA   oWSGETLISTAETIQUETASRESULT AS PORTALLICENCIADO_RETLISTAETIQUETAS
	WSDATA   oWSGETLISTALANCAVENDARESULT AS PORTALLICENCIADO_RETLISTALANCAVENDA
	WSDATA   cCZA_CODPDV               AS string
	WSDATA   oWSGETLISTAPRODUTOSRESULT AS PORTALLICENCIADO_RETLISTAPRODUTOS
	WSDATA   oWSGETLOGINPORTALSCIRESULT AS PORTALLICENCIADO_RETRESULTLOGIN
	WSDATA   cCZA_CODPRO               AS string
	WSDATA   oWSGETSALVAPRODUTOSRESULT AS PORTALLICENCIADO_RETSALVAPRODUTOS
	WSDATA   oWSGETVISUALIZALANCRESULT AS PORTALLICENCIADO_RETVISUALIZALANC

ENDWSCLIENT

WSMETHOD NEW WSCLIENT WSPORTALLICENCIADO
::Init()
If !FindFunction("XMLCHILDEX")
	UserException("O Código-Fonte Client atual requer os executáveis do Protheus Build [7.00.131227A-20140829] ou superior. Atualize o Protheus ou gere o Código-Fonte novamente utilizando o Build atual.")
EndIf
Return Self

WSMETHOD INIT WSCLIENT WSPORTALLICENCIADO
	::oWSGETATUALIZATIQUETARESULT := PORTALLICENCIADO_RETATUALIZAETIQUETA():New()
	::oWSGETATUALIZAVENDASRESULT := PORTALLICENCIADO_RETATUALIZAVENDAS():New()
	::oWSGETESQUECISENHARESULT := PORTALLICENCIADO_RETESQUECISENHA():New()
	::oWSGETIMPRIMIBOLETORESULT := PORTALLICENCIADO_RETIMPRIMIBOLETO():New()
	::oWSGETLISTACONTRATOSRESULT := PORTALLICENCIADO_RETLISTACONTRATOS():New()
	::oWSGETLISTAETIQUETASRESULT := PORTALLICENCIADO_RETLISTAETIQUETAS():New()
	::oWSGETLISTALANCAVENDARESULT := PORTALLICENCIADO_RETLISTALANCAVENDA():New()
	::oWSGETLISTAPRODUTOSRESULT := PORTALLICENCIADO_RETLISTAPRODUTOS():New()
	::oWSGETLOGINPORTALSCIRESULT := PORTALLICENCIADO_RETRESULTLOGIN():New()
	::oWSGETSALVAPRODUTOSRESULT := PORTALLICENCIADO_RETSALVAPRODUTOS():New()
	::oWSGETVISUALIZALANCRESULT := PORTALLICENCIADO_RETVISUALIZALANC():New()
Return

WSMETHOD RESET WSCLIENT WSPORTALLICENCIADO
	::cCWEMPRESA         := NIL 
	::cCWFILIAL          := NIL 
	::cCWSUSUARIO        := NIL 
	::cCWSSENHA          := NIL 
	::cCCNPJ             := NIL 
	::cCCHVPORTAL        := NIL 
	::cCTIPOLOGIN        := NIL 
	::cCTIPOOPER         := NIL 
	::cCDTENTREGA        := NIL 
	::cCQUANTETIQ        := NIL 
	::cCCNPJCLIENTE      := NIL 
	::oWSGETATUALIZATIQUETARESULT := NIL 
	::cCZ9_NUMCTO        := NIL 
	::cCZ9_REVCTO        := NIL 
	::cCZ9_CODCLI        := NIL 
	::cCZ9_LOJCLI        := NIL 
	::cCZ9_PERIODO       := NIL 
	::cCZ9_DTINIPE       := NIL 
	::cCZ9_DTFIMPE       := NIL 
	::cCZ9_VALOR         := NIL 
	::cCZ9_CGC           := NIL 
	::cCZ9_VLRLIQ        := NIL 
	::cCZ9_QUANT         := NIL 
	::oWSGETATUALIZAVENDASRESULT := NIL 
	::oWSGETESQUECISENHARESULT := NIL 
	::cCZ9_PREFIXO       := NIL 
	::cCZ9_NUM           := NIL 
	::cCZ9_PARCELA       := NIL 
	::cCZ9_TIPO          := NIL 
	::cCZ9_CLIENTE       := NIL 
	::cCZ9_LOJA          := NIL 
	::oWSGETIMPRIMIBOLETORESULT := NIL 
	::oWSGETLISTACONTRATOSRESULT := NIL 
	::oWSGETLISTAETIQUETASRESULT := NIL 
	::oWSGETLISTALANCAVENDARESULT := NIL 
	::cCZA_CODPDV        := NIL 
	::oWSGETLISTAPRODUTOSRESULT := NIL 
	::oWSGETLOGINPORTALSCIRESULT := NIL 
	::cCZA_CODPRO        := NIL 
	::oWSGETSALVAPRODUTOSRESULT := NIL 
	::oWSGETVISUALIZALANCRESULT := NIL 
	::Init()
Return

WSMETHOD CLONE WSCLIENT WSPORTALLICENCIADO
Local oClone := WSPORTALLICENCIADO():New()
	oClone:_URL          := ::_URL 
	oClone:cCWEMPRESA    := ::cCWEMPRESA
	oClone:cCWFILIAL     := ::cCWFILIAL
	oClone:cCWSUSUARIO   := ::cCWSUSUARIO
	oClone:cCWSSENHA     := ::cCWSSENHA
	oClone:cCCNPJ        := ::cCCNPJ
	oClone:cCCHVPORTAL   := ::cCCHVPORTAL
	oClone:cCTIPOLOGIN   := ::cCTIPOLOGIN
	oClone:cCTIPOOPER    := ::cCTIPOOPER
	oClone:cCDTENTREGA   := ::cCDTENTREGA
	oClone:cCQUANTETIQ   := ::cCQUANTETIQ
	oClone:cCCNPJCLIENTE := ::cCCNPJCLIENTE
	oClone:oWSGETATUALIZATIQUETARESULT :=  IIF(::oWSGETATUALIZATIQUETARESULT = NIL , NIL ,::oWSGETATUALIZATIQUETARESULT:Clone() )
	oClone:cCZ9_NUMCTO   := ::cCZ9_NUMCTO
	oClone:cCZ9_REVCTO   := ::cCZ9_REVCTO
	oClone:cCZ9_CODCLI   := ::cCZ9_CODCLI
	oClone:cCZ9_LOJCLI   := ::cCZ9_LOJCLI
	oClone:cCZ9_PERIODO  := ::cCZ9_PERIODO
	oClone:cCZ9_DTINIPE  := ::cCZ9_DTINIPE
	oClone:cCZ9_DTFIMPE  := ::cCZ9_DTFIMPE
	oClone:cCZ9_VALOR    := ::cCZ9_VALOR
	oClone:cCZ9_CGC      := ::cCZ9_CGC
	oClone:cCZ9_VLRLIQ   := ::cCZ9_VLRLIQ
	oClone:cCZ9_QUANT    := ::cCZ9_QUANT
	oClone:oWSGETATUALIZAVENDASRESULT :=  IIF(::oWSGETATUALIZAVENDASRESULT = NIL , NIL ,::oWSGETATUALIZAVENDASRESULT:Clone() )
	oClone:oWSGETESQUECISENHARESULT :=  IIF(::oWSGETESQUECISENHARESULT = NIL , NIL ,::oWSGETESQUECISENHARESULT:Clone() )
	oClone:cCZ9_PREFIXO  := ::cCZ9_PREFIXO
	oClone:cCZ9_NUM      := ::cCZ9_NUM
	oClone:cCZ9_PARCELA  := ::cCZ9_PARCELA
	oClone:cCZ9_TIPO     := ::cCZ9_TIPO
	oClone:cCZ9_CLIENTE  := ::cCZ9_CLIENTE
	oClone:cCZ9_LOJA     := ::cCZ9_LOJA
	oClone:oWSGETIMPRIMIBOLETORESULT :=  IIF(::oWSGETIMPRIMIBOLETORESULT = NIL , NIL ,::oWSGETIMPRIMIBOLETORESULT:Clone() )
	oClone:oWSGETLISTACONTRATOSRESULT :=  IIF(::oWSGETLISTACONTRATOSRESULT = NIL , NIL ,::oWSGETLISTACONTRATOSRESULT:Clone() )
	oClone:oWSGETLISTAETIQUETASRESULT :=  IIF(::oWSGETLISTAETIQUETASRESULT = NIL , NIL ,::oWSGETLISTAETIQUETASRESULT:Clone() )
	oClone:oWSGETLISTALANCAVENDARESULT :=  IIF(::oWSGETLISTALANCAVENDARESULT = NIL , NIL ,::oWSGETLISTALANCAVENDARESULT:Clone() )
	oClone:cCZA_CODPDV   := ::cCZA_CODPDV
	oClone:oWSGETLISTAPRODUTOSRESULT :=  IIF(::oWSGETLISTAPRODUTOSRESULT = NIL , NIL ,::oWSGETLISTAPRODUTOSRESULT:Clone() )
	oClone:oWSGETLOGINPORTALSCIRESULT :=  IIF(::oWSGETLOGINPORTALSCIRESULT = NIL , NIL ,::oWSGETLOGINPORTALSCIRESULT:Clone() )
	oClone:cCZA_CODPRO   := ::cCZA_CODPRO
	oClone:oWSGETSALVAPRODUTOSRESULT :=  IIF(::oWSGETSALVAPRODUTOSRESULT = NIL , NIL ,::oWSGETSALVAPRODUTOSRESULT:Clone() )
	oClone:oWSGETVISUALIZALANCRESULT :=  IIF(::oWSGETVISUALIZALANCRESULT = NIL , NIL ,::oWSGETVISUALIZALANCRESULT:Clone() )
Return oClone

// WSDL Method GETATUALIZATIQUETA of Service WSPORTALLICENCIADO

WSMETHOD GETATUALIZATIQUETA WSSEND cCWEMPRESA,cCWFILIAL,cCWSUSUARIO,cCWSSENHA,cCCNPJ,cCCHVPORTAL,cCTIPOLOGIN,cCTIPOOPER,cCDTENTREGA,cCQUANTETIQ,cCCNPJCLIENTE WSRECEIVE oWSGETATUALIZATIQUETARESULT WSCLIENT WSPORTALLICENCIADO
Local cSoap := "" , oXmlRet

BEGIN WSMETHOD

cSoap += '<GETATUALIZATIQUETA xmlns="http://10.100.0.5:8091/">'
cSoap += WSSoapValue("CWEMPRESA", ::cCWEMPRESA, cCWEMPRESA , "string", .T. , .F., 0 , NIL, .F.) 
cSoap += WSSoapValue("CWFILIAL", ::cCWFILIAL, cCWFILIAL , "string", .T. , .F., 0 , NIL, .F.) 
cSoap += WSSoapValue("CWSUSUARIO", ::cCWSUSUARIO, cCWSUSUARIO , "string", .T. , .F., 0 , NIL, .F.) 
cSoap += WSSoapValue("CWSSENHA", ::cCWSSENHA, cCWSSENHA , "string", .T. , .F., 0 , NIL, .F.) 
cSoap += WSSoapValue("CCNPJ", ::cCCNPJ, cCCNPJ , "string", .T. , .F., 0 , NIL, .F.) 
cSoap += WSSoapValue("CCHVPORTAL", ::cCCHVPORTAL, cCCHVPORTAL , "string", .T. , .F., 0 , NIL, .F.) 
cSoap += WSSoapValue("CTIPOLOGIN", ::cCTIPOLOGIN, cCTIPOLOGIN , "string", .T. , .F., 0 , NIL, .F.) 
cSoap += WSSoapValue("CTIPOOPER", ::cCTIPOOPER, cCTIPOOPER , "string", .T. , .F., 0 , NIL, .F.) 
cSoap += WSSoapValue("CDTENTREGA", ::cCDTENTREGA, cCDTENTREGA , "string", .T. , .F., 0 , NIL, .F.) 
cSoap += WSSoapValue("CQUANTETIQ", ::cCQUANTETIQ, cCQUANTETIQ , "string", .T. , .F., 0 , NIL, .F.) 
cSoap += WSSoapValue("CCNPJCLIENTE", ::cCCNPJCLIENTE, cCCNPJCLIENTE , "string", .T. , .F., 0 , NIL, .F.) 
cSoap += "</GETATUALIZATIQUETA>"

oXmlRet := SvcSoapCall(	Self,cSoap,; 
	"http://10.100.0.5:8091/GETATUALIZATIQUETA",; 
	"DOCUMENT","http://10.100.0.5:8091/",,"1.031217",; 
	"http://10.100.0.5:8091/ws/PORTALLICENCIADO.apw")

::Init()
::oWSGETATUALIZATIQUETARESULT:SoapRecv( WSAdvValue( oXmlRet,"_GETATUALIZATIQUETARESPONSE:_GETATUALIZATIQUETARESULT","RETATUALIZAETIQUETA",NIL,NIL,NIL,NIL,NIL,NIL) )

END WSMETHOD

oXmlRet := NIL
Return .T.

// WSDL Method GETATUALIZAVENDAS of Service WSPORTALLICENCIADO

WSMETHOD GETATUALIZAVENDAS WSSEND cCWEMPRESA,cCWFILIAL,cCWSUSUARIO,cCWSSENHA,cCCNPJ,cCCHVPORTAL,cCTIPOLOGIN,cCZ9_NUMCTO,cCZ9_REVCTO,cCZ9_CODCLI,cCZ9_LOJCLI,cCZ9_PERIODO,cCZ9_DTINIPE,cCZ9_DTFIMPE,cCZ9_VALOR,cCZ9_CGC,cCTIPOOPER,cCZ9_VLRLIQ,cCZ9_QUANT WSRECEIVE oWSGETATUALIZAVENDASRESULT WSCLIENT WSPORTALLICENCIADO
Local cSoap := "" , oXmlRet

BEGIN WSMETHOD

cSoap += '<GETATUALIZAVENDAS xmlns="http://10.100.0.5:8091/">'
cSoap += WSSoapValue("CWEMPRESA", ::cCWEMPRESA, cCWEMPRESA , "string", .T. , .F., 0 , NIL, .F.) 
cSoap += WSSoapValue("CWFILIAL", ::cCWFILIAL, cCWFILIAL , "string", .T. , .F., 0 , NIL, .F.) 
cSoap += WSSoapValue("CWSUSUARIO", ::cCWSUSUARIO, cCWSUSUARIO , "string", .T. , .F., 0 , NIL, .F.) 
cSoap += WSSoapValue("CWSSENHA", ::cCWSSENHA, cCWSSENHA , "string", .T. , .F., 0 , NIL, .F.) 
cSoap += WSSoapValue("CCNPJ", ::cCCNPJ, cCCNPJ , "string", .T. , .F., 0 , NIL, .F.) 
cSoap += WSSoapValue("CCHVPORTAL", ::cCCHVPORTAL, cCCHVPORTAL , "string", .T. , .F., 0 , NIL, .F.) 
cSoap += WSSoapValue("CTIPOLOGIN", ::cCTIPOLOGIN, cCTIPOLOGIN , "string", .T. , .F., 0 , NIL, .F.) 
cSoap += WSSoapValue("CZ9_NUMCTO", ::cCZ9_NUMCTO, cCZ9_NUMCTO , "string", .T. , .F., 0 , NIL, .F.) 
cSoap += WSSoapValue("CZ9_REVCTO", ::cCZ9_REVCTO, cCZ9_REVCTO , "string", .T. , .F., 0 , NIL, .F.) 
cSoap += WSSoapValue("CZ9_CODCLI", ::cCZ9_CODCLI, cCZ9_CODCLI , "string", .T. , .F., 0 , NIL, .F.) 
cSoap += WSSoapValue("CZ9_LOJCLI", ::cCZ9_LOJCLI, cCZ9_LOJCLI , "string", .T. , .F., 0 , NIL, .F.) 
cSoap += WSSoapValue("CZ9_PERIODO", ::cCZ9_PERIODO, cCZ9_PERIODO , "string", .T. , .F., 0 , NIL, .F.) 
cSoap += WSSoapValue("CZ9_DTINIPE", ::cCZ9_DTINIPE, cCZ9_DTINIPE , "string", .T. , .F., 0 , NIL, .F.) 
cSoap += WSSoapValue("CZ9_DTFIMPE", ::cCZ9_DTFIMPE, cCZ9_DTFIMPE , "string", .T. , .F., 0 , NIL, .F.) 
cSoap += WSSoapValue("CZ9_VALOR", ::cCZ9_VALOR, cCZ9_VALOR , "string", .T. , .F., 0 , NIL, .F.) 
cSoap += WSSoapValue("CZ9_CGC", ::cCZ9_CGC, cCZ9_CGC , "string", .T. , .F., 0 , NIL, .F.) 
cSoap += WSSoapValue("CTIPOOPER", ::cCTIPOOPER, cCTIPOOPER , "string", .T. , .F., 0 , NIL, .F.) 
cSoap += WSSoapValue("CZ9_VLRLIQ", ::cCZ9_VLRLIQ, cCZ9_VLRLIQ , "string", .T. , .F., 0 , NIL, .F.) 
cSoap += WSSoapValue("CZ9_QUANT", ::cCZ9_QUANT, cCZ9_QUANT , "string", .T. , .F., 0 , NIL, .F.) 
cSoap += "</GETATUALIZAVENDAS>"

oXmlRet := SvcSoapCall(	Self,cSoap,; 
	"http://10.100.0.5:8091/GETATUALIZAVENDAS",; 
	"DOCUMENT","http://10.100.0.5:8091/",,"1.031217",; 
	"http://10.100.0.5:8091/ws/PORTALLICENCIADO.apw")

::Init()
::oWSGETATUALIZAVENDASRESULT:SoapRecv( WSAdvValue( oXmlRet,"_GETATUALIZAVENDASRESPONSE:_GETATUALIZAVENDASRESULT","RETATUALIZAVENDAS",NIL,NIL,NIL,NIL,NIL,NIL) )

END WSMETHOD

oXmlRet := NIL
Return .T.

// WSDL Method GETESQUECISENHA of Service WSPORTALLICENCIADO

WSMETHOD GETESQUECISENHA WSSEND cCWEMPRESA,cCWFILIAL,cCWSUSUARIO,cCWSSENHA,cCCNPJ,cCTIPOLOGIN WSRECEIVE oWSGETESQUECISENHARESULT WSCLIENT WSPORTALLICENCIADO
Local cSoap := "" , oXmlRet

BEGIN WSMETHOD

cSoap += '<GETESQUECISENHA xmlns="http://10.100.0.5:8091/">'
cSoap += WSSoapValue("CWEMPRESA", ::cCWEMPRESA, cCWEMPRESA , "string", .T. , .F., 0 , NIL, .F.) 
cSoap += WSSoapValue("CWFILIAL", ::cCWFILIAL, cCWFILIAL , "string", .T. , .F., 0 , NIL, .F.) 
cSoap += WSSoapValue("CWSUSUARIO", ::cCWSUSUARIO, cCWSUSUARIO , "string", .T. , .F., 0 , NIL, .F.) 
cSoap += WSSoapValue("CWSSENHA", ::cCWSSENHA, cCWSSENHA , "string", .T. , .F., 0 , NIL, .F.) 
cSoap += WSSoapValue("CCNPJ", ::cCCNPJ, cCCNPJ , "string", .T. , .F., 0 , NIL, .F.) 
cSoap += WSSoapValue("CTIPOLOGIN", ::cCTIPOLOGIN, cCTIPOLOGIN , "string", .T. , .F., 0 , NIL, .F.) 
cSoap += "</GETESQUECISENHA>"

oXmlRet := SvcSoapCall(	Self,cSoap,; 
	"http://10.100.0.5:8091/GETESQUECISENHA",; 
	"DOCUMENT","http://10.100.0.5:8091/",,"1.031217",; 
	"http://10.100.0.5:8091/ws/PORTALLICENCIADO.apw")

::Init()
::oWSGETESQUECISENHARESULT:SoapRecv( WSAdvValue( oXmlRet,"_GETESQUECISENHARESPONSE:_GETESQUECISENHARESULT","RETESQUECISENHA",NIL,NIL,NIL,NIL,NIL,NIL) )

END WSMETHOD

oXmlRet := NIL
Return .T.

// WSDL Method GETIMPRIMIBOLETO of Service WSPORTALLICENCIADO

WSMETHOD GETIMPRIMIBOLETO WSSEND cCWEMPRESA,cCWFILIAL,cCWSUSUARIO,cCWSSENHA,cCCNPJ,cCCHVPORTAL,cCTIPOLOGIN,cCZ9_PERIODO,cCZ9_PREFIXO,cCZ9_NUM,cCZ9_PARCELA,cCZ9_TIPO,cCZ9_CLIENTE,cCZ9_LOJA WSRECEIVE oWSGETIMPRIMIBOLETORESULT WSCLIENT WSPORTALLICENCIADO
Local cSoap := "" , oXmlRet

BEGIN WSMETHOD

cSoap += '<GETIMPRIMIBOLETO xmlns="http://10.100.0.5:8091/">'
cSoap += WSSoapValue("CWEMPRESA", ::cCWEMPRESA, cCWEMPRESA , "string", .T. , .F., 0 , NIL, .F.) 
cSoap += WSSoapValue("CWFILIAL", ::cCWFILIAL, cCWFILIAL , "string", .T. , .F., 0 , NIL, .F.) 
cSoap += WSSoapValue("CWSUSUARIO", ::cCWSUSUARIO, cCWSUSUARIO , "string", .T. , .F., 0 , NIL, .F.) 
cSoap += WSSoapValue("CWSSENHA", ::cCWSSENHA, cCWSSENHA , "string", .T. , .F., 0 , NIL, .F.) 
cSoap += WSSoapValue("CCNPJ", ::cCCNPJ, cCCNPJ , "string", .T. , .F., 0 , NIL, .F.) 
cSoap += WSSoapValue("CCHVPORTAL", ::cCCHVPORTAL, cCCHVPORTAL , "string", .T. , .F., 0 , NIL, .F.) 
cSoap += WSSoapValue("CTIPOLOGIN", ::cCTIPOLOGIN, cCTIPOLOGIN , "string", .T. , .F., 0 , NIL, .F.) 
cSoap += WSSoapValue("CZ9_PERIODO", ::cCZ9_PERIODO, cCZ9_PERIODO , "string", .T. , .F., 0 , NIL, .F.) 
cSoap += WSSoapValue("CZ9_PREFIXO", ::cCZ9_PREFIXO, cCZ9_PREFIXO , "string", .T. , .F., 0 , NIL, .F.) 
cSoap += WSSoapValue("CZ9_NUM", ::cCZ9_NUM, cCZ9_NUM , "string", .T. , .F., 0 , NIL, .F.) 
cSoap += WSSoapValue("CZ9_PARCELA", ::cCZ9_PARCELA, cCZ9_PARCELA , "string", .T. , .F., 0 , NIL, .F.) 
cSoap += WSSoapValue("CZ9_TIPO", ::cCZ9_TIPO, cCZ9_TIPO , "string", .T. , .F., 0 , NIL, .F.) 
cSoap += WSSoapValue("CZ9_CLIENTE", ::cCZ9_CLIENTE, cCZ9_CLIENTE , "string", .T. , .F., 0 , NIL, .F.) 
cSoap += WSSoapValue("CZ9_LOJA", ::cCZ9_LOJA, cCZ9_LOJA , "string", .T. , .F., 0 , NIL, .F.) 
cSoap += "</GETIMPRIMIBOLETO>"

oXmlRet := SvcSoapCall(	Self,cSoap,; 
	"http://10.100.0.5:8091/GETIMPRIMIBOLETO",; 
	"DOCUMENT","http://10.100.0.5:8091/",,"1.031217",; 
	"http://10.100.0.5:8091/ws/PORTALLICENCIADO.apw")

::Init()
::oWSGETIMPRIMIBOLETORESULT:SoapRecv( WSAdvValue( oXmlRet,"_GETIMPRIMIBOLETORESPONSE:_GETIMPRIMIBOLETORESULT","RETIMPRIMIBOLETO",NIL,NIL,NIL,NIL,NIL,NIL) )

END WSMETHOD

oXmlRet := NIL
Return .T.

// WSDL Method GETLISTACONTRATOS of Service WSPORTALLICENCIADO

WSMETHOD GETLISTACONTRATOS WSSEND cCWEMPRESA,cCWFILIAL,cCWSUSUARIO,cCWSSENHA,cCCNPJ,cCCHVPORTAL,cCTIPOLOGIN WSRECEIVE oWSGETLISTACONTRATOSRESULT WSCLIENT WSPORTALLICENCIADO
Local cSoap := "" , oXmlRet

BEGIN WSMETHOD

cSoap += '<GETLISTACONTRATOS xmlns="http://10.100.0.5:8091/">'
cSoap += WSSoapValue("CWEMPRESA", ::cCWEMPRESA, cCWEMPRESA , "string", .T. , .F., 0 , NIL, .F.) 
cSoap += WSSoapValue("CWFILIAL", ::cCWFILIAL, cCWFILIAL , "string", .T. , .F., 0 , NIL, .F.) 
cSoap += WSSoapValue("CWSUSUARIO", ::cCWSUSUARIO, cCWSUSUARIO , "string", .T. , .F., 0 , NIL, .F.) 
cSoap += WSSoapValue("CWSSENHA", ::cCWSSENHA, cCWSSENHA , "string", .T. , .F., 0 , NIL, .F.) 
cSoap += WSSoapValue("CCNPJ", ::cCCNPJ, cCCNPJ , "string", .T. , .F., 0 , NIL, .F.) 
cSoap += WSSoapValue("CCHVPORTAL", ::cCCHVPORTAL, cCCHVPORTAL , "string", .T. , .F., 0 , NIL, .F.) 
cSoap += WSSoapValue("CTIPOLOGIN", ::cCTIPOLOGIN, cCTIPOLOGIN , "string", .T. , .F., 0 , NIL, .F.) 
cSoap += "</GETLISTACONTRATOS>"

oXmlRet := SvcSoapCall(	Self,cSoap,; 
	"http://10.100.0.5:8091/GETLISTACONTRATOS",; 
	"DOCUMENT","http://10.100.0.5:8091/",,"1.031217",; 
	"http://10.100.0.5:8091/ws/PORTALLICENCIADO.apw")

::Init()
::oWSGETLISTACONTRATOSRESULT:SoapRecv( WSAdvValue( oXmlRet,"_GETLISTACONTRATOSRESPONSE:_GETLISTACONTRATOSRESULT","RETLISTACONTRATOS",NIL,NIL,NIL,NIL,NIL,NIL) )

END WSMETHOD

oXmlRet := NIL
Return .T.

// WSDL Method GETLISTAETIQUETAS of Service WSPORTALLICENCIADO

WSMETHOD GETLISTAETIQUETAS WSSEND cCWEMPRESA,cCWFILIAL,cCWSUSUARIO,cCWSSENHA,cCCNPJ,cCCHVPORTAL,cCTIPOLOGIN WSRECEIVE oWSGETLISTAETIQUETASRESULT WSCLIENT WSPORTALLICENCIADO
Local cSoap := "" , oXmlRet

BEGIN WSMETHOD

cSoap += '<GETLISTAETIQUETAS xmlns="http://10.100.0.5:8091/">'
cSoap += WSSoapValue("CWEMPRESA", ::cCWEMPRESA, cCWEMPRESA , "string", .T. , .F., 0 , NIL, .F.) 
cSoap += WSSoapValue("CWFILIAL", ::cCWFILIAL, cCWFILIAL , "string", .T. , .F., 0 , NIL, .F.) 
cSoap += WSSoapValue("CWSUSUARIO", ::cCWSUSUARIO, cCWSUSUARIO , "string", .T. , .F., 0 , NIL, .F.) 
cSoap += WSSoapValue("CWSSENHA", ::cCWSSENHA, cCWSSENHA , "string", .T. , .F., 0 , NIL, .F.) 
cSoap += WSSoapValue("CCNPJ", ::cCCNPJ, cCCNPJ , "string", .T. , .F., 0 , NIL, .F.) 
cSoap += WSSoapValue("CCHVPORTAL", ::cCCHVPORTAL, cCCHVPORTAL , "string", .T. , .F., 0 , NIL, .F.) 
cSoap += WSSoapValue("CTIPOLOGIN", ::cCTIPOLOGIN, cCTIPOLOGIN , "string", .T. , .F., 0 , NIL, .F.) 
cSoap += "</GETLISTAETIQUETAS>"

oXmlRet := SvcSoapCall(	Self,cSoap,; 
	"http://10.100.0.5:8091/GETLISTAETIQUETAS",; 
	"DOCUMENT","http://10.100.0.5:8091/",,"1.031217",; 
	"http://10.100.0.5:8091/ws/PORTALLICENCIADO.apw")

::Init()
::oWSGETLISTAETIQUETASRESULT:SoapRecv( WSAdvValue( oXmlRet,"_GETLISTAETIQUETASRESPONSE:_GETLISTAETIQUETASRESULT","RETLISTAETIQUETAS",NIL,NIL,NIL,NIL,NIL,NIL) )

END WSMETHOD

oXmlRet := NIL
Return .T.

// WSDL Method GETLISTALANCAVENDA of Service WSPORTALLICENCIADO

WSMETHOD GETLISTALANCAVENDA WSSEND cCWEMPRESA,cCWFILIAL,cCWSUSUARIO,cCWSSENHA,cCCNPJ,cCCHVPORTAL,cCTIPOLOGIN,cCZ9_NUMCTO WSRECEIVE oWSGETLISTALANCAVENDARESULT WSCLIENT WSPORTALLICENCIADO
Local cSoap := "" , oXmlRet

BEGIN WSMETHOD

cSoap += '<GETLISTALANCAVENDA xmlns="http://10.100.0.5:8091/">'
cSoap += WSSoapValue("CWEMPRESA", ::cCWEMPRESA, cCWEMPRESA , "string", .T. , .F., 0 , NIL, .F.) 
cSoap += WSSoapValue("CWFILIAL", ::cCWFILIAL, cCWFILIAL , "string", .T. , .F., 0 , NIL, .F.) 
cSoap += WSSoapValue("CWSUSUARIO", ::cCWSUSUARIO, cCWSUSUARIO , "string", .T. , .F., 0 , NIL, .F.) 
cSoap += WSSoapValue("CWSSENHA", ::cCWSSENHA, cCWSSENHA , "string", .T. , .F., 0 , NIL, .F.) 
cSoap += WSSoapValue("CCNPJ", ::cCCNPJ, cCCNPJ , "string", .T. , .F., 0 , NIL, .F.) 
cSoap += WSSoapValue("CCHVPORTAL", ::cCCHVPORTAL, cCCHVPORTAL , "string", .T. , .F., 0 , NIL, .F.) 
cSoap += WSSoapValue("CTIPOLOGIN", ::cCTIPOLOGIN, cCTIPOLOGIN , "string", .T. , .F., 0 , NIL, .F.) 
cSoap += WSSoapValue("CZ9_NUMCTO", ::cCZ9_NUMCTO, cCZ9_NUMCTO , "string", .T. , .F., 0 , NIL, .F.) 
cSoap += "</GETLISTALANCAVENDA>"

oXmlRet := SvcSoapCall(	Self,cSoap,; 
	"http://10.100.0.5:8091/GETLISTALANCAVENDA",; 
	"DOCUMENT","http://10.100.0.5:8091/",,"1.031217",; 
	"http://10.100.0.5:8091/ws/PORTALLICENCIADO.apw")

::Init()
::oWSGETLISTALANCAVENDARESULT:SoapRecv( WSAdvValue( oXmlRet,"_GETLISTALANCAVENDARESPONSE:_GETLISTALANCAVENDARESULT","RETLISTALANCAVENDA",NIL,NIL,NIL,NIL,NIL,NIL) )

END WSMETHOD

oXmlRet := NIL
Return .T.

// WSDL Method GETLISTAPRODUTOS of Service WSPORTALLICENCIADO

WSMETHOD GETLISTAPRODUTOS WSSEND cCWEMPRESA,cCWFILIAL,cCWSUSUARIO,cCWSSENHA,cCCNPJ,cCCHVPORTAL,cCTIPOLOGIN,cCZ9_NUMCTO,cCZ9_REVCTO,cCZ9_CODCLI,cCZ9_LOJCLI,cCZ9_PERIODO,cCZ9_DTINIPE,cCZ9_DTFIMPE,cCZA_CODPDV WSRECEIVE oWSGETLISTAPRODUTOSRESULT WSCLIENT WSPORTALLICENCIADO
Local cSoap := "" , oXmlRet

BEGIN WSMETHOD

cSoap += '<GETLISTAPRODUTOS xmlns="http://10.100.0.5:8091/">'
cSoap += WSSoapValue("CWEMPRESA", ::cCWEMPRESA, cCWEMPRESA , "string", .T. , .F., 0 , NIL, .F.) 
cSoap += WSSoapValue("CWFILIAL", ::cCWFILIAL, cCWFILIAL , "string", .T. , .F., 0 , NIL, .F.) 
cSoap += WSSoapValue("CWSUSUARIO", ::cCWSUSUARIO, cCWSUSUARIO , "string", .T. , .F., 0 , NIL, .F.) 
cSoap += WSSoapValue("CWSSENHA", ::cCWSSENHA, cCWSSENHA , "string", .T. , .F., 0 , NIL, .F.) 
cSoap += WSSoapValue("CCNPJ", ::cCCNPJ, cCCNPJ , "string", .T. , .F., 0 , NIL, .F.) 
cSoap += WSSoapValue("CCHVPORTAL", ::cCCHVPORTAL, cCCHVPORTAL , "string", .T. , .F., 0 , NIL, .F.) 
cSoap += WSSoapValue("CTIPOLOGIN", ::cCTIPOLOGIN, cCTIPOLOGIN , "string", .T. , .F., 0 , NIL, .F.) 
cSoap += WSSoapValue("CZ9_NUMCTO", ::cCZ9_NUMCTO, cCZ9_NUMCTO , "string", .T. , .F., 0 , NIL, .F.) 
cSoap += WSSoapValue("CZ9_REVCTO", ::cCZ9_REVCTO, cCZ9_REVCTO , "string", .T. , .F., 0 , NIL, .F.) 
cSoap += WSSoapValue("CZ9_CODCLI", ::cCZ9_CODCLI, cCZ9_CODCLI , "string", .T. , .F., 0 , NIL, .F.) 
cSoap += WSSoapValue("CZ9_LOJCLI", ::cCZ9_LOJCLI, cCZ9_LOJCLI , "string", .T. , .F., 0 , NIL, .F.) 
cSoap += WSSoapValue("CZ9_PERIODO", ::cCZ9_PERIODO, cCZ9_PERIODO , "string", .T. , .F., 0 , NIL, .F.) 
cSoap += WSSoapValue("CZ9_DTINIPE", ::cCZ9_DTINIPE, cCZ9_DTINIPE , "string", .T. , .F., 0 , NIL, .F.) 
cSoap += WSSoapValue("CZ9_DTFIMPE", ::cCZ9_DTFIMPE, cCZ9_DTFIMPE , "string", .T. , .F., 0 , NIL, .F.) 
cSoap += WSSoapValue("CZA_CODPDV", ::cCZA_CODPDV, cCZA_CODPDV , "string", .T. , .F., 0 , NIL, .F.) 
cSoap += "</GETLISTAPRODUTOS>"

oXmlRet := SvcSoapCall(	Self,cSoap,; 
	"http://10.100.0.5:8091/GETLISTAPRODUTOS",; 
	"DOCUMENT","http://10.100.0.5:8091/",,"1.031217",; 
	"http://10.100.0.5:8091/ws/PORTALLICENCIADO.apw")

::Init()
::oWSGETLISTAPRODUTOSRESULT:SoapRecv( WSAdvValue( oXmlRet,"_GETLISTAPRODUTOSRESPONSE:_GETLISTAPRODUTOSRESULT","RETLISTAPRODUTOS",NIL,NIL,NIL,NIL,NIL,NIL) )

END WSMETHOD

oXmlRet := NIL
Return .T.

// WSDL Method GETLOGINPORTALSCI of Service WSPORTALLICENCIADO

WSMETHOD GETLOGINPORTALSCI WSSEND cCWEMPRESA,cCWFILIAL,cCWSUSUARIO,cCWSSENHA,cCCNPJ,cCCHVPORTAL,cCTIPOLOGIN WSRECEIVE oWSGETLOGINPORTALSCIRESULT WSCLIENT WSPORTALLICENCIADO
Local cSoap := "" , oXmlRet

BEGIN WSMETHOD

cSoap += '<GETLOGINPORTALSCI xmlns="http://10.100.0.5:8091/">'
cSoap += WSSoapValue("CWEMPRESA", ::cCWEMPRESA, cCWEMPRESA , "string", .T. , .F., 0 , NIL, .F.) 
cSoap += WSSoapValue("CWFILIAL", ::cCWFILIAL, cCWFILIAL , "string", .T. , .F., 0 , NIL, .F.) 
cSoap += WSSoapValue("CWSUSUARIO", ::cCWSUSUARIO, cCWSUSUARIO , "string", .T. , .F., 0 , NIL, .F.) 
cSoap += WSSoapValue("CWSSENHA", ::cCWSSENHA, cCWSSENHA , "string", .T. , .F., 0 , NIL, .F.) 
cSoap += WSSoapValue("CCNPJ", ::cCCNPJ, cCCNPJ , "string", .T. , .F., 0 , NIL, .F.) 
cSoap += WSSoapValue("CCHVPORTAL", ::cCCHVPORTAL, cCCHVPORTAL , "string", .T. , .F., 0 , NIL, .F.) 
cSoap += WSSoapValue("CTIPOLOGIN", ::cCTIPOLOGIN, cCTIPOLOGIN , "string", .T. , .F., 0 , NIL, .F.) 
cSoap += "</GETLOGINPORTALSCI>"

oXmlRet := SvcSoapCall(	Self,cSoap,; 
	"http://10.100.0.5:8091/GETLOGINPORTALSCI",; 
	"DOCUMENT","http://10.100.0.5:8091/",,"1.031217",; 
	"http://10.100.0.5:8091/ws/PORTALLICENCIADO.apw")

::Init()
::oWSGETLOGINPORTALSCIRESULT:SoapRecv( WSAdvValue( oXmlRet,"_GETLOGINPORTALSCIRESPONSE:_GETLOGINPORTALSCIRESULT","RETRESULTLOGIN",NIL,NIL,NIL,NIL,NIL,NIL) )

END WSMETHOD

oXmlRet := NIL
Return .T.

// WSDL Method GETSALVAPRODUTOS of Service WSPORTALLICENCIADO

WSMETHOD GETSALVAPRODUTOS WSSEND cCWEMPRESA,cCWFILIAL,cCWSUSUARIO,cCWSSENHA,cCCNPJ,cCCHVPORTAL,cCTIPOLOGIN,cCZ9_NUMCTO,cCZ9_REVCTO,cCZ9_CODCLI,cCZ9_LOJCLI,cCZ9_PERIODO,cCZ9_DTINIPE,cCZ9_DTFIMPE,cCZA_CODPDV,cCZA_CODPRO WSRECEIVE oWSGETSALVAPRODUTOSRESULT WSCLIENT WSPORTALLICENCIADO
Local cSoap := "" , oXmlRet

BEGIN WSMETHOD

cSoap += '<GETSALVAPRODUTOS xmlns="http://10.100.0.5:8091/">'
cSoap += WSSoapValue("CWEMPRESA", ::cCWEMPRESA, cCWEMPRESA , "string", .T. , .F., 0 , NIL, .F.) 
cSoap += WSSoapValue("CWFILIAL", ::cCWFILIAL, cCWFILIAL , "string", .T. , .F., 0 , NIL, .F.) 
cSoap += WSSoapValue("CWSUSUARIO", ::cCWSUSUARIO, cCWSUSUARIO , "string", .T. , .F., 0 , NIL, .F.) 
cSoap += WSSoapValue("CWSSENHA", ::cCWSSENHA, cCWSSENHA , "string", .T. , .F., 0 , NIL, .F.) 
cSoap += WSSoapValue("CCNPJ", ::cCCNPJ, cCCNPJ , "string", .T. , .F., 0 , NIL, .F.) 
cSoap += WSSoapValue("CCHVPORTAL", ::cCCHVPORTAL, cCCHVPORTAL , "string", .T. , .F., 0 , NIL, .F.) 
cSoap += WSSoapValue("CTIPOLOGIN", ::cCTIPOLOGIN, cCTIPOLOGIN , "string", .T. , .F., 0 , NIL, .F.) 
cSoap += WSSoapValue("CZ9_NUMCTO", ::cCZ9_NUMCTO, cCZ9_NUMCTO , "string", .T. , .F., 0 , NIL, .F.) 
cSoap += WSSoapValue("CZ9_REVCTO", ::cCZ9_REVCTO, cCZ9_REVCTO , "string", .T. , .F., 0 , NIL, .F.) 
cSoap += WSSoapValue("CZ9_CODCLI", ::cCZ9_CODCLI, cCZ9_CODCLI , "string", .T. , .F., 0 , NIL, .F.) 
cSoap += WSSoapValue("CZ9_LOJCLI", ::cCZ9_LOJCLI, cCZ9_LOJCLI , "string", .T. , .F., 0 , NIL, .F.) 
cSoap += WSSoapValue("CZ9_PERIODO", ::cCZ9_PERIODO, cCZ9_PERIODO , "string", .T. , .F., 0 , NIL, .F.) 
cSoap += WSSoapValue("CZ9_DTINIPE", ::cCZ9_DTINIPE, cCZ9_DTINIPE , "string", .T. , .F., 0 , NIL, .F.) 
cSoap += WSSoapValue("CZ9_DTFIMPE", ::cCZ9_DTFIMPE, cCZ9_DTFIMPE , "string", .T. , .F., 0 , NIL, .F.) 
cSoap += WSSoapValue("CZA_CODPDV", ::cCZA_CODPDV, cCZA_CODPDV , "string", .T. , .F., 0 , NIL, .F.) 
cSoap += WSSoapValue("CZA_CODPRO", ::cCZA_CODPRO, cCZA_CODPRO , "string", .T. , .F., 0 , NIL, .F.) 
cSoap += "</GETSALVAPRODUTOS>"

oXmlRet := SvcSoapCall(	Self,cSoap,; 
	"http://10.100.0.5:8091/GETSALVAPRODUTOS",; 
	"DOCUMENT","http://10.100.0.5:8091/",,"1.031217",; 
	"http://10.100.0.5:8091/ws/PORTALLICENCIADO.apw")

::Init()
::oWSGETSALVAPRODUTOSRESULT:SoapRecv( WSAdvValue( oXmlRet,"_GETSALVAPRODUTOSRESPONSE:_GETSALVAPRODUTOSRESULT","RETSALVAPRODUTOS",NIL,NIL,NIL,NIL,NIL,NIL) )

END WSMETHOD

oXmlRet := NIL
Return .T.

// WSDL Method GETVISUALIZALANC of Service WSPORTALLICENCIADO

WSMETHOD GETVISUALIZALANC WSSEND cCWEMPRESA,cCWFILIAL,cCWSUSUARIO,cCWSSENHA,cCCNPJ,cCCHVPORTAL,cCTIPOLOGIN,cCZ9_NUMCTO,cCZ9_REVCTO,cCZ9_CODCLI,cCZ9_LOJCLI,cCZ9_PERIODO,cCZ9_DTINIPE,cCZ9_DTFIMPE,cCZ9_CGC WSRECEIVE oWSGETVISUALIZALANCRESULT WSCLIENT WSPORTALLICENCIADO
Local cSoap := "" , oXmlRet

BEGIN WSMETHOD

cSoap += '<GETVISUALIZALANC xmlns="http://10.100.0.5:8091/">'
cSoap += WSSoapValue("CWEMPRESA", ::cCWEMPRESA, cCWEMPRESA , "string", .T. , .F., 0 , NIL, .F.) 
cSoap += WSSoapValue("CWFILIAL", ::cCWFILIAL, cCWFILIAL , "string", .T. , .F., 0 , NIL, .F.) 
cSoap += WSSoapValue("CWSUSUARIO", ::cCWSUSUARIO, cCWSUSUARIO , "string", .T. , .F., 0 , NIL, .F.) 
cSoap += WSSoapValue("CWSSENHA", ::cCWSSENHA, cCWSSENHA , "string", .T. , .F., 0 , NIL, .F.) 
cSoap += WSSoapValue("CCNPJ", ::cCCNPJ, cCCNPJ , "string", .T. , .F., 0 , NIL, .F.) 
cSoap += WSSoapValue("CCHVPORTAL", ::cCCHVPORTAL, cCCHVPORTAL , "string", .T. , .F., 0 , NIL, .F.) 
cSoap += WSSoapValue("CTIPOLOGIN", ::cCTIPOLOGIN, cCTIPOLOGIN , "string", .T. , .F., 0 , NIL, .F.) 
cSoap += WSSoapValue("CZ9_NUMCTO", ::cCZ9_NUMCTO, cCZ9_NUMCTO , "string", .T. , .F., 0 , NIL, .F.) 
cSoap += WSSoapValue("CZ9_REVCTO", ::cCZ9_REVCTO, cCZ9_REVCTO , "string", .T. , .F., 0 , NIL, .F.) 
cSoap += WSSoapValue("CZ9_CODCLI", ::cCZ9_CODCLI, cCZ9_CODCLI , "string", .T. , .F., 0 , NIL, .F.) 
cSoap += WSSoapValue("CZ9_LOJCLI", ::cCZ9_LOJCLI, cCZ9_LOJCLI , "string", .T. , .F., 0 , NIL, .F.) 
cSoap += WSSoapValue("CZ9_PERIODO", ::cCZ9_PERIODO, cCZ9_PERIODO , "string", .T. , .F., 0 , NIL, .F.) 
cSoap += WSSoapValue("CZ9_DTINIPE", ::cCZ9_DTINIPE, cCZ9_DTINIPE , "string", .T. , .F., 0 , NIL, .F.) 
cSoap += WSSoapValue("CZ9_DTFIMPE", ::cCZ9_DTFIMPE, cCZ9_DTFIMPE , "string", .T. , .F., 0 , NIL, .F.) 
cSoap += WSSoapValue("CZ9_CGC", ::cCZ9_CGC, cCZ9_CGC , "string", .T. , .F., 0 , NIL, .F.) 
cSoap += "</GETVISUALIZALANC>"

oXmlRet := SvcSoapCall(	Self,cSoap,; 
	"http://10.100.0.5:8091/GETVISUALIZALANC",; 
	"DOCUMENT","http://10.100.0.5:8091/",,"1.031217",; 
	"http://10.100.0.5:8091/ws/PORTALLICENCIADO.apw")

::Init()
::oWSGETVISUALIZALANCRESULT:SoapRecv( WSAdvValue( oXmlRet,"_GETVISUALIZALANCRESPONSE:_GETVISUALIZALANCRESULT","RETVISUALIZALANC",NIL,NIL,NIL,NIL,NIL,NIL) )

END WSMETHOD

oXmlRet := NIL
Return .T.


// WSDL Data Structure RETATUALIZAETIQUETA

WSSTRUCT PORTALLICENCIADO_RETATUALIZAETIQUETA
	WSDATA   c_LSTATUSRET              AS string
	WSDATA   cCMSGRET                  AS string
	WSMETHOD NEW
	WSMETHOD INIT
	WSMETHOD CLONE
	WSMETHOD SOAPRECV
ENDWSSTRUCT

WSMETHOD NEW WSCLIENT PORTALLICENCIADO_RETATUALIZAETIQUETA
	::Init()
Return Self

WSMETHOD INIT WSCLIENT PORTALLICENCIADO_RETATUALIZAETIQUETA
Return

WSMETHOD CLONE WSCLIENT PORTALLICENCIADO_RETATUALIZAETIQUETA
	Local oClone := PORTALLICENCIADO_RETATUALIZAETIQUETA():NEW()
	oClone:c_LSTATUSRET         := ::c_LSTATUSRET
	oClone:cCMSGRET             := ::cCMSGRET
Return oClone

WSMETHOD SOAPRECV WSSEND oResponse WSCLIENT PORTALLICENCIADO_RETATUALIZAETIQUETA
	::Init()
	If oResponse = NIL ; Return ; Endif 
	::c_LSTATUSRET       :=  WSAdvValue( oResponse,"__LSTATUSRET","string",NIL,"Property c_LSTATUSRET as s:string on SOAP Response not found.",NIL,"S",NIL,NIL) 
	::cCMSGRET           :=  WSAdvValue( oResponse,"_CMSGRET","string",NIL,"Property cCMSGRET as s:string on SOAP Response not found.",NIL,"S",NIL,NIL) 
Return

// WSDL Data Structure RETATUALIZAVENDAS

WSSTRUCT PORTALLICENCIADO_RETATUALIZAVENDAS
	WSDATA   c_LRETATU                 AS string
	WSDATA   cCMSGATU                  AS string
	WSMETHOD NEW
	WSMETHOD INIT
	WSMETHOD CLONE
	WSMETHOD SOAPRECV
ENDWSSTRUCT

WSMETHOD NEW WSCLIENT PORTALLICENCIADO_RETATUALIZAVENDAS
	::Init()
Return Self

WSMETHOD INIT WSCLIENT PORTALLICENCIADO_RETATUALIZAVENDAS
Return

WSMETHOD CLONE WSCLIENT PORTALLICENCIADO_RETATUALIZAVENDAS
	Local oClone := PORTALLICENCIADO_RETATUALIZAVENDAS():NEW()
	oClone:c_LRETATU            := ::c_LRETATU
	oClone:cCMSGATU             := ::cCMSGATU
Return oClone

WSMETHOD SOAPRECV WSSEND oResponse WSCLIENT PORTALLICENCIADO_RETATUALIZAVENDAS
	::Init()
	If oResponse = NIL ; Return ; Endif 
	::c_LRETATU          :=  WSAdvValue( oResponse,"__LRETATU","string",NIL,"Property c_LRETATU as s:string on SOAP Response not found.",NIL,"S",NIL,NIL) 
	::cCMSGATU           :=  WSAdvValue( oResponse,"_CMSGATU","string",NIL,"Property cCMSGATU as s:string on SOAP Response not found.",NIL,"S",NIL,NIL) 
Return

// WSDL Data Structure RETESQUECISENHA

WSSTRUCT PORTALLICENCIADO_RETESQUECISENHA
	WSDATA   c_LESQUECISENHA           AS string
	WSDATA   cCMSGESQUECI              AS string
	WSMETHOD NEW
	WSMETHOD INIT
	WSMETHOD CLONE
	WSMETHOD SOAPRECV
ENDWSSTRUCT

WSMETHOD NEW WSCLIENT PORTALLICENCIADO_RETESQUECISENHA
	::Init()
Return Self

WSMETHOD INIT WSCLIENT PORTALLICENCIADO_RETESQUECISENHA
Return

WSMETHOD CLONE WSCLIENT PORTALLICENCIADO_RETESQUECISENHA
	Local oClone := PORTALLICENCIADO_RETESQUECISENHA():NEW()
	oClone:c_LESQUECISENHA      := ::c_LESQUECISENHA
	oClone:cCMSGESQUECI         := ::cCMSGESQUECI
Return oClone

WSMETHOD SOAPRECV WSSEND oResponse WSCLIENT PORTALLICENCIADO_RETESQUECISENHA
	::Init()
	If oResponse = NIL ; Return ; Endif 
	::c_LESQUECISENHA    :=  WSAdvValue( oResponse,"__LESQUECISENHA","string",NIL,"Property c_LESQUECISENHA as s:string on SOAP Response not found.",NIL,"S",NIL,NIL) 
	::cCMSGESQUECI       :=  WSAdvValue( oResponse,"_CMSGESQUECI","string",NIL,"Property cCMSGESQUECI as s:string on SOAP Response not found.",NIL,"S",NIL,NIL) 
Return

// WSDL Data Structure RETIMPRIMIBOLETO

WSSTRUCT PORTALLICENCIADO_RETIMPRIMIBOLETO
	WSDATA   c_LRETBOLETO              AS string
	WSDATA   cCLINKBOLETO              AS string
	WSMETHOD NEW
	WSMETHOD INIT
	WSMETHOD CLONE
	WSMETHOD SOAPRECV
ENDWSSTRUCT

WSMETHOD NEW WSCLIENT PORTALLICENCIADO_RETIMPRIMIBOLETO
	::Init()
Return Self

WSMETHOD INIT WSCLIENT PORTALLICENCIADO_RETIMPRIMIBOLETO
Return

WSMETHOD CLONE WSCLIENT PORTALLICENCIADO_RETIMPRIMIBOLETO
	Local oClone := PORTALLICENCIADO_RETIMPRIMIBOLETO():NEW()
	oClone:c_LRETBOLETO         := ::c_LRETBOLETO
	oClone:cCLINKBOLETO         := ::cCLINKBOLETO
Return oClone

WSMETHOD SOAPRECV WSSEND oResponse WSCLIENT PORTALLICENCIADO_RETIMPRIMIBOLETO
	::Init()
	If oResponse = NIL ; Return ; Endif 
	::c_LRETBOLETO       :=  WSAdvValue( oResponse,"__LRETBOLETO","string",NIL,"Property c_LRETBOLETO as s:string on SOAP Response not found.",NIL,"S",NIL,NIL) 
	::cCLINKBOLETO       :=  WSAdvValue( oResponse,"_CLINKBOLETO","string",NIL,"Property cCLINKBOLETO as s:string on SOAP Response not found.",NIL,"S",NIL,NIL) 
Return

// WSDL Data Structure RETLISTACONTRATOS

WSSTRUCT PORTALLICENCIADO_RETLISTACONTRATOS
	WSDATA   oWS_STATUSSCI             AS PORTALLICENCIADO_ARRAYOFSCISTATUS
	WSDATA   oWSRETDADOSSCI            AS PORTALLICENCIADO_ARRAYOFDADOSCONTRATOS
	WSMETHOD NEW
	WSMETHOD INIT
	WSMETHOD CLONE
	WSMETHOD SOAPRECV
ENDWSSTRUCT

WSMETHOD NEW WSCLIENT PORTALLICENCIADO_RETLISTACONTRATOS
	::Init()
Return Self

WSMETHOD INIT WSCLIENT PORTALLICENCIADO_RETLISTACONTRATOS
Return

WSMETHOD CLONE WSCLIENT PORTALLICENCIADO_RETLISTACONTRATOS
	Local oClone := PORTALLICENCIADO_RETLISTACONTRATOS():NEW()
	oClone:oWS_STATUSSCI        := IIF(::oWS_STATUSSCI = NIL , NIL , ::oWS_STATUSSCI:Clone() )
	oClone:oWSRETDADOSSCI       := IIF(::oWSRETDADOSSCI = NIL , NIL , ::oWSRETDADOSSCI:Clone() )
Return oClone

WSMETHOD SOAPRECV WSSEND oResponse WSCLIENT PORTALLICENCIADO_RETLISTACONTRATOS
	Local oNode1
	Local oNode2
	::Init()
	If oResponse = NIL ; Return ; Endif 
	oNode1 :=  WSAdvValue( oResponse,"__STATUSSCI","ARRAYOFSCISTATUS",NIL,"Property oWS_STATUSSCI as s0:ARRAYOFSCISTATUS on SOAP Response not found.",NIL,"O",NIL,NIL) 
	If oNode1 != NIL
		::oWS_STATUSSCI := PORTALLICENCIADO_ARRAYOFSCISTATUS():New()
		::oWS_STATUSSCI:SoapRecv(oNode1)
	EndIf
	oNode2 :=  WSAdvValue( oResponse,"_RETDADOSSCI","ARRAYOFDADOSCONTRATOS",NIL,"Property oWSRETDADOSSCI as s0:ARRAYOFDADOSCONTRATOS on SOAP Response not found.",NIL,"O",NIL,NIL) 
	If oNode2 != NIL
		::oWSRETDADOSSCI := PORTALLICENCIADO_ARRAYOFDADOSCONTRATOS():New()
		::oWSRETDADOSSCI:SoapRecv(oNode2)
	EndIf
Return

// WSDL Data Structure RETLISTAETIQUETAS

WSSTRUCT PORTALLICENCIADO_RETLISTAETIQUETAS
	WSDATA   oWS_LRETLISTAETQ          AS PORTALLICENCIADO_ARRAYOFSTATUSETIQUETA
	WSDATA   oWSCRETLISTAETQ           AS PORTALLICENCIADO_ARRAYOFSTRUTLISTAETQ
	WSMETHOD NEW
	WSMETHOD INIT
	WSMETHOD CLONE
	WSMETHOD SOAPRECV
ENDWSSTRUCT

WSMETHOD NEW WSCLIENT PORTALLICENCIADO_RETLISTAETIQUETAS
	::Init()
Return Self

WSMETHOD INIT WSCLIENT PORTALLICENCIADO_RETLISTAETIQUETAS
Return

WSMETHOD CLONE WSCLIENT PORTALLICENCIADO_RETLISTAETIQUETAS
	Local oClone := PORTALLICENCIADO_RETLISTAETIQUETAS():NEW()
	oClone:oWS_LRETLISTAETQ     := IIF(::oWS_LRETLISTAETQ = NIL , NIL , ::oWS_LRETLISTAETQ:Clone() )
	oClone:oWSCRETLISTAETQ      := IIF(::oWSCRETLISTAETQ = NIL , NIL , ::oWSCRETLISTAETQ:Clone() )
Return oClone

WSMETHOD SOAPRECV WSSEND oResponse WSCLIENT PORTALLICENCIADO_RETLISTAETIQUETAS
	Local oNode1
	Local oNode2
	::Init()
	If oResponse = NIL ; Return ; Endif 
	oNode1 :=  WSAdvValue( oResponse,"__LRETLISTAETQ","ARRAYOFSTATUSETIQUETA",NIL,"Property oWS_LRETLISTAETQ as s0:ARRAYOFSTATUSETIQUETA on SOAP Response not found.",NIL,"O",NIL,NIL) 
	If oNode1 != NIL
		::oWS_LRETLISTAETQ := PORTALLICENCIADO_ARRAYOFSTATUSETIQUETA():New()
		::oWS_LRETLISTAETQ:SoapRecv(oNode1)
	EndIf
	oNode2 :=  WSAdvValue( oResponse,"_CRETLISTAETQ","ARRAYOFSTRUTLISTAETQ",NIL,"Property oWSCRETLISTAETQ as s0:ARRAYOFSTRUTLISTAETQ on SOAP Response not found.",NIL,"O",NIL,NIL) 
	If oNode2 != NIL
		::oWSCRETLISTAETQ := PORTALLICENCIADO_ARRAYOFSTRUTLISTAETQ():New()
		::oWSCRETLISTAETQ:SoapRecv(oNode2)
	EndIf
Return

// WSDL Data Structure RETLISTALANCAVENDA

WSSTRUCT PORTALLICENCIADO_RETLISTALANCAVENDA
	WSDATA   oWS_STATUSLLV             AS PORTALLICENCIADO_ARRAYOFSCISTATUSLLV
	WSDATA   oWSRETLANCVENDAS          AS PORTALLICENCIADO_ARRAYOFDADOSLANCVENDAS
	WSMETHOD NEW
	WSMETHOD INIT
	WSMETHOD CLONE
	WSMETHOD SOAPRECV
ENDWSSTRUCT

WSMETHOD NEW WSCLIENT PORTALLICENCIADO_RETLISTALANCAVENDA
	::Init()
Return Self

WSMETHOD INIT WSCLIENT PORTALLICENCIADO_RETLISTALANCAVENDA
Return

WSMETHOD CLONE WSCLIENT PORTALLICENCIADO_RETLISTALANCAVENDA
	Local oClone := PORTALLICENCIADO_RETLISTALANCAVENDA():NEW()
	oClone:oWS_STATUSLLV        := IIF(::oWS_STATUSLLV = NIL , NIL , ::oWS_STATUSLLV:Clone() )
	oClone:oWSRETLANCVENDAS     := IIF(::oWSRETLANCVENDAS = NIL , NIL , ::oWSRETLANCVENDAS:Clone() )
Return oClone

WSMETHOD SOAPRECV WSSEND oResponse WSCLIENT PORTALLICENCIADO_RETLISTALANCAVENDA
	Local oNode1
	Local oNode2
	::Init()
	If oResponse = NIL ; Return ; Endif 
	oNode1 :=  WSAdvValue( oResponse,"__STATUSLLV","ARRAYOFSCISTATUSLLV",NIL,"Property oWS_STATUSLLV as s0:ARRAYOFSCISTATUSLLV on SOAP Response not found.",NIL,"O",NIL,NIL) 
	If oNode1 != NIL
		::oWS_STATUSLLV := PORTALLICENCIADO_ARRAYOFSCISTATUSLLV():New()
		::oWS_STATUSLLV:SoapRecv(oNode1)
	EndIf
	oNode2 :=  WSAdvValue( oResponse,"_RETLANCVENDAS","ARRAYOFDADOSLANCVENDAS",NIL,"Property oWSRETLANCVENDAS as s0:ARRAYOFDADOSLANCVENDAS on SOAP Response not found.",NIL,"O",NIL,NIL) 
	If oNode2 != NIL
		::oWSRETLANCVENDAS := PORTALLICENCIADO_ARRAYOFDADOSLANCVENDAS():New()
		::oWSRETLANCVENDAS:SoapRecv(oNode2)
	EndIf
Return

// WSDL Data Structure RETLISTAPRODUTOS

WSSTRUCT PORTALLICENCIADO_RETLISTAPRODUTOS
	WSDATA   oWSARETPRODUTO            AS PORTALLICENCIADO_ARRAYOFSTRUTPRODUTOS
	WSMETHOD NEW
	WSMETHOD INIT
	WSMETHOD CLONE
	WSMETHOD SOAPRECV
ENDWSSTRUCT

WSMETHOD NEW WSCLIENT PORTALLICENCIADO_RETLISTAPRODUTOS
	::Init()
Return Self

WSMETHOD INIT WSCLIENT PORTALLICENCIADO_RETLISTAPRODUTOS
Return

WSMETHOD CLONE WSCLIENT PORTALLICENCIADO_RETLISTAPRODUTOS
	Local oClone := PORTALLICENCIADO_RETLISTAPRODUTOS():NEW()
	oClone:oWSARETPRODUTO       := IIF(::oWSARETPRODUTO = NIL , NIL , ::oWSARETPRODUTO:Clone() )
Return oClone

WSMETHOD SOAPRECV WSSEND oResponse WSCLIENT PORTALLICENCIADO_RETLISTAPRODUTOS
	Local oNode1
	::Init()
	If oResponse = NIL ; Return ; Endif 
	oNode1 :=  WSAdvValue( oResponse,"_ARETPRODUTO","ARRAYOFSTRUTPRODUTOS",NIL,"Property oWSARETPRODUTO as s0:ARRAYOFSTRUTPRODUTOS on SOAP Response not found.",NIL,"O",NIL,NIL) 
	If oNode1 != NIL
		::oWSARETPRODUTO := PORTALLICENCIADO_ARRAYOFSTRUTPRODUTOS():New()
		::oWSARETPRODUTO:SoapRecv(oNode1)
	EndIf
Return

// WSDL Data Structure RETRESULTLOGIN

WSSTRUCT PORTALLICENCIADO_RETRESULTLOGIN
	WSDATA   oWSRETLOGINPORTAL         AS PORTALLICENCIADO_ARRAYOFDADOSLOGINPORTAL
	WSDATA   oWSRETLOJALIC             AS PORTALLICENCIADO_ARRAYOFLOJASLICENCIADO
	WSMETHOD NEW
	WSMETHOD INIT
	WSMETHOD CLONE
	WSMETHOD SOAPRECV
ENDWSSTRUCT

WSMETHOD NEW WSCLIENT PORTALLICENCIADO_RETRESULTLOGIN
	::Init()
Return Self

WSMETHOD INIT WSCLIENT PORTALLICENCIADO_RETRESULTLOGIN
Return

WSMETHOD CLONE WSCLIENT PORTALLICENCIADO_RETRESULTLOGIN
	Local oClone := PORTALLICENCIADO_RETRESULTLOGIN():NEW()
	oClone:oWSRETLOGINPORTAL    := IIF(::oWSRETLOGINPORTAL = NIL , NIL , ::oWSRETLOGINPORTAL:Clone() )
	oClone:oWSRETLOJALIC        := IIF(::oWSRETLOJALIC = NIL , NIL , ::oWSRETLOJALIC:Clone() )
Return oClone

WSMETHOD SOAPRECV WSSEND oResponse WSCLIENT PORTALLICENCIADO_RETRESULTLOGIN
	Local oNode1
	Local oNode2
	::Init()
	If oResponse = NIL ; Return ; Endif 
	oNode1 :=  WSAdvValue( oResponse,"_RETLOGINPORTAL","ARRAYOFDADOSLOGINPORTAL",NIL,"Property oWSRETLOGINPORTAL as s0:ARRAYOFDADOSLOGINPORTAL on SOAP Response not found.",NIL,"O",NIL,NIL) 
	If oNode1 != NIL
		::oWSRETLOGINPORTAL := PORTALLICENCIADO_ARRAYOFDADOSLOGINPORTAL():New()
		::oWSRETLOGINPORTAL:SoapRecv(oNode1)
	EndIf
	oNode2 :=  WSAdvValue( oResponse,"_RETLOJALIC","ARRAYOFLOJASLICENCIADO",NIL,"Property oWSRETLOJALIC as s0:ARRAYOFLOJASLICENCIADO on SOAP Response not found.",NIL,"O",NIL,NIL) 
	If oNode2 != NIL
		::oWSRETLOJALIC := PORTALLICENCIADO_ARRAYOFLOJASLICENCIADO():New()
		::oWSRETLOJALIC:SoapRecv(oNode2)
	EndIf
Return

// WSDL Data Structure RETSALVAPRODUTOS

WSSTRUCT PORTALLICENCIADO_RETSALVAPRODUTOS
	WSDATA   oWSARETGRAVAPROD          AS PORTALLICENCIADO_ARRAYOFSTRUTPROD
	WSMETHOD NEW
	WSMETHOD INIT
	WSMETHOD CLONE
	WSMETHOD SOAPRECV
ENDWSSTRUCT

WSMETHOD NEW WSCLIENT PORTALLICENCIADO_RETSALVAPRODUTOS
	::Init()
Return Self

WSMETHOD INIT WSCLIENT PORTALLICENCIADO_RETSALVAPRODUTOS
Return

WSMETHOD CLONE WSCLIENT PORTALLICENCIADO_RETSALVAPRODUTOS
	Local oClone := PORTALLICENCIADO_RETSALVAPRODUTOS():NEW()
	oClone:oWSARETGRAVAPROD     := IIF(::oWSARETGRAVAPROD = NIL , NIL , ::oWSARETGRAVAPROD:Clone() )
Return oClone

WSMETHOD SOAPRECV WSSEND oResponse WSCLIENT PORTALLICENCIADO_RETSALVAPRODUTOS
	Local oNode1
	::Init()
	If oResponse = NIL ; Return ; Endif 
	oNode1 :=  WSAdvValue( oResponse,"_ARETGRAVAPROD","ARRAYOFSTRUTPROD",NIL,"Property oWSARETGRAVAPROD as s0:ARRAYOFSTRUTPROD on SOAP Response not found.",NIL,"O",NIL,NIL) 
	If oNode1 != NIL
		::oWSARETGRAVAPROD := PORTALLICENCIADO_ARRAYOFSTRUTPROD():New()
		::oWSARETGRAVAPROD:SoapRecv(oNode1)
	EndIf
Return

// WSDL Data Structure RETVISUALIZALANC

WSSTRUCT PORTALLICENCIADO_RETVISUALIZALANC
	WSDATA   oWS_LRETSTATUSVIS         AS PORTALLICENCIADO_ARRAYOFSTATUSVISUAL
	WSDATA   oWSCRETVISUALANC          AS PORTALLICENCIADO_ARRAYOFSTRUTVISUALLANC
	WSMETHOD NEW
	WSMETHOD INIT
	WSMETHOD CLONE
	WSMETHOD SOAPRECV
ENDWSSTRUCT

WSMETHOD NEW WSCLIENT PORTALLICENCIADO_RETVISUALIZALANC
	::Init()
Return Self

WSMETHOD INIT WSCLIENT PORTALLICENCIADO_RETVISUALIZALANC
Return

WSMETHOD CLONE WSCLIENT PORTALLICENCIADO_RETVISUALIZALANC
	Local oClone := PORTALLICENCIADO_RETVISUALIZALANC():NEW()
	oClone:oWS_LRETSTATUSVIS    := IIF(::oWS_LRETSTATUSVIS = NIL , NIL , ::oWS_LRETSTATUSVIS:Clone() )
	oClone:oWSCRETVISUALANC     := IIF(::oWSCRETVISUALANC = NIL , NIL , ::oWSCRETVISUALANC:Clone() )
Return oClone

WSMETHOD SOAPRECV WSSEND oResponse WSCLIENT PORTALLICENCIADO_RETVISUALIZALANC
	Local oNode1
	Local oNode2
	::Init()
	If oResponse = NIL ; Return ; Endif 
	oNode1 :=  WSAdvValue( oResponse,"__LRETSTATUSVIS","ARRAYOFSTATUSVISUAL",NIL,"Property oWS_LRETSTATUSVIS as s0:ARRAYOFSTATUSVISUAL on SOAP Response not found.",NIL,"O",NIL,NIL) 
	If oNode1 != NIL
		::oWS_LRETSTATUSVIS := PORTALLICENCIADO_ARRAYOFSTATUSVISUAL():New()
		::oWS_LRETSTATUSVIS:SoapRecv(oNode1)
	EndIf
	oNode2 :=  WSAdvValue( oResponse,"_CRETVISUALANC","ARRAYOFSTRUTVISUALLANC",NIL,"Property oWSCRETVISUALANC as s0:ARRAYOFSTRUTVISUALLANC on SOAP Response not found.",NIL,"O",NIL,NIL) 
	If oNode2 != NIL
		::oWSCRETVISUALANC := PORTALLICENCIADO_ARRAYOFSTRUTVISUALLANC():New()
		::oWSCRETVISUALANC:SoapRecv(oNode2)
	EndIf
Return

// WSDL Data Structure ARRAYOFSCISTATUS

WSSTRUCT PORTALLICENCIADO_ARRAYOFSCISTATUS
	WSDATA   oWSSCISTATUS              AS PORTALLICENCIADO_SCISTATUS OPTIONAL
	WSMETHOD NEW
	WSMETHOD INIT
	WSMETHOD CLONE
	WSMETHOD SOAPRECV
ENDWSSTRUCT

WSMETHOD NEW WSCLIENT PORTALLICENCIADO_ARRAYOFSCISTATUS
	::Init()
Return Self

WSMETHOD INIT WSCLIENT PORTALLICENCIADO_ARRAYOFSCISTATUS
	::oWSSCISTATUS         := {} // Array Of  PORTALLICENCIADO_SCISTATUS():New()
Return

WSMETHOD CLONE WSCLIENT PORTALLICENCIADO_ARRAYOFSCISTATUS
	Local oClone := PORTALLICENCIADO_ARRAYOFSCISTATUS():NEW()
	oClone:oWSSCISTATUS := NIL
	If ::oWSSCISTATUS <> NIL 
		oClone:oWSSCISTATUS := {}
		aEval( ::oWSSCISTATUS , { |x| aadd( oClone:oWSSCISTATUS , x:Clone() ) } )
	Endif 
Return oClone

WSMETHOD SOAPRECV WSSEND oResponse WSCLIENT PORTALLICENCIADO_ARRAYOFSCISTATUS
	Local nRElem1, oNodes1, nTElem1
	::Init()
	If oResponse = NIL ; Return ; Endif 
	oNodes1 :=  WSAdvValue( oResponse,"_SCISTATUS","SCISTATUS",{},NIL,.T.,"O",NIL,NIL) 
	nTElem1 := len(oNodes1)
	For nRElem1 := 1 to nTElem1 
		If !WSIsNilNode( oNodes1[nRElem1] )
			aadd(::oWSSCISTATUS , PORTALLICENCIADO_SCISTATUS():New() )
			::oWSSCISTATUS[len(::oWSSCISTATUS)]:SoapRecv(oNodes1[nRElem1])
		Endif
	Next
Return

// WSDL Data Structure ARRAYOFDADOSCONTRATOS

WSSTRUCT PORTALLICENCIADO_ARRAYOFDADOSCONTRATOS
	WSDATA   oWSDADOSCONTRATOS         AS PORTALLICENCIADO_DADOSCONTRATOS OPTIONAL
	WSMETHOD NEW
	WSMETHOD INIT
	WSMETHOD CLONE
	WSMETHOD SOAPRECV
ENDWSSTRUCT

WSMETHOD NEW WSCLIENT PORTALLICENCIADO_ARRAYOFDADOSCONTRATOS
	::Init()
Return Self

WSMETHOD INIT WSCLIENT PORTALLICENCIADO_ARRAYOFDADOSCONTRATOS
	::oWSDADOSCONTRATOS    := {} // Array Of  PORTALLICENCIADO_DADOSCONTRATOS():New()
Return

WSMETHOD CLONE WSCLIENT PORTALLICENCIADO_ARRAYOFDADOSCONTRATOS
	Local oClone := PORTALLICENCIADO_ARRAYOFDADOSCONTRATOS():NEW()
	oClone:oWSDADOSCONTRATOS := NIL
	If ::oWSDADOSCONTRATOS <> NIL 
		oClone:oWSDADOSCONTRATOS := {}
		aEval( ::oWSDADOSCONTRATOS , { |x| aadd( oClone:oWSDADOSCONTRATOS , x:Clone() ) } )
	Endif 
Return oClone

WSMETHOD SOAPRECV WSSEND oResponse WSCLIENT PORTALLICENCIADO_ARRAYOFDADOSCONTRATOS
	Local nRElem1, oNodes1, nTElem1
	::Init()
	If oResponse = NIL ; Return ; Endif 
	oNodes1 :=  WSAdvValue( oResponse,"_DADOSCONTRATOS","DADOSCONTRATOS",{},NIL,.T.,"O",NIL,NIL) 
	nTElem1 := len(oNodes1)
	For nRElem1 := 1 to nTElem1 
		If !WSIsNilNode( oNodes1[nRElem1] )
			aadd(::oWSDADOSCONTRATOS , PORTALLICENCIADO_DADOSCONTRATOS():New() )
			::oWSDADOSCONTRATOS[len(::oWSDADOSCONTRATOS)]:SoapRecv(oNodes1[nRElem1])
		Endif
	Next
Return

// WSDL Data Structure ARRAYOFSTATUSETIQUETA

WSSTRUCT PORTALLICENCIADO_ARRAYOFSTATUSETIQUETA
	WSDATA   oWSSTATUSETIQUETA         AS PORTALLICENCIADO_STATUSETIQUETA OPTIONAL
	WSMETHOD NEW
	WSMETHOD INIT
	WSMETHOD CLONE
	WSMETHOD SOAPRECV
ENDWSSTRUCT

WSMETHOD NEW WSCLIENT PORTALLICENCIADO_ARRAYOFSTATUSETIQUETA
	::Init()
Return Self

WSMETHOD INIT WSCLIENT PORTALLICENCIADO_ARRAYOFSTATUSETIQUETA
	::oWSSTATUSETIQUETA    := {} // Array Of  PORTALLICENCIADO_STATUSETIQUETA():New()
Return

WSMETHOD CLONE WSCLIENT PORTALLICENCIADO_ARRAYOFSTATUSETIQUETA
	Local oClone := PORTALLICENCIADO_ARRAYOFSTATUSETIQUETA():NEW()
	oClone:oWSSTATUSETIQUETA := NIL
	If ::oWSSTATUSETIQUETA <> NIL 
		oClone:oWSSTATUSETIQUETA := {}
		aEval( ::oWSSTATUSETIQUETA , { |x| aadd( oClone:oWSSTATUSETIQUETA , x:Clone() ) } )
	Endif 
Return oClone

WSMETHOD SOAPRECV WSSEND oResponse WSCLIENT PORTALLICENCIADO_ARRAYOFSTATUSETIQUETA
	Local nRElem1, oNodes1, nTElem1
	::Init()
	If oResponse = NIL ; Return ; Endif 
	oNodes1 :=  WSAdvValue( oResponse,"_STATUSETIQUETA","STATUSETIQUETA",{},NIL,.T.,"O",NIL,NIL) 
	nTElem1 := len(oNodes1)
	For nRElem1 := 1 to nTElem1 
		If !WSIsNilNode( oNodes1[nRElem1] )
			aadd(::oWSSTATUSETIQUETA , PORTALLICENCIADO_STATUSETIQUETA():New() )
			::oWSSTATUSETIQUETA[len(::oWSSTATUSETIQUETA)]:SoapRecv(oNodes1[nRElem1])
		Endif
	Next
Return

// WSDL Data Structure ARRAYOFSTRUTLISTAETQ

WSSTRUCT PORTALLICENCIADO_ARRAYOFSTRUTLISTAETQ
	WSDATA   oWSSTRUTLISTAETQ          AS PORTALLICENCIADO_STRUTLISTAETQ OPTIONAL
	WSMETHOD NEW
	WSMETHOD INIT
	WSMETHOD CLONE
	WSMETHOD SOAPRECV
ENDWSSTRUCT

WSMETHOD NEW WSCLIENT PORTALLICENCIADO_ARRAYOFSTRUTLISTAETQ
	::Init()
Return Self

WSMETHOD INIT WSCLIENT PORTALLICENCIADO_ARRAYOFSTRUTLISTAETQ
	::oWSSTRUTLISTAETQ     := {} // Array Of  PORTALLICENCIADO_STRUTLISTAETQ():New()
Return

WSMETHOD CLONE WSCLIENT PORTALLICENCIADO_ARRAYOFSTRUTLISTAETQ
	Local oClone := PORTALLICENCIADO_ARRAYOFSTRUTLISTAETQ():NEW()
	oClone:oWSSTRUTLISTAETQ := NIL
	If ::oWSSTRUTLISTAETQ <> NIL 
		oClone:oWSSTRUTLISTAETQ := {}
		aEval( ::oWSSTRUTLISTAETQ , { |x| aadd( oClone:oWSSTRUTLISTAETQ , x:Clone() ) } )
	Endif 
Return oClone

WSMETHOD SOAPRECV WSSEND oResponse WSCLIENT PORTALLICENCIADO_ARRAYOFSTRUTLISTAETQ
	Local nRElem1, oNodes1, nTElem1
	::Init()
	If oResponse = NIL ; Return ; Endif 
	oNodes1 :=  WSAdvValue( oResponse,"_STRUTLISTAETQ","STRUTLISTAETQ",{},NIL,.T.,"O",NIL,NIL) 
	nTElem1 := len(oNodes1)
	For nRElem1 := 1 to nTElem1 
		If !WSIsNilNode( oNodes1[nRElem1] )
			aadd(::oWSSTRUTLISTAETQ , PORTALLICENCIADO_STRUTLISTAETQ():New() )
			::oWSSTRUTLISTAETQ[len(::oWSSTRUTLISTAETQ)]:SoapRecv(oNodes1[nRElem1])
		Endif
	Next
Return

// WSDL Data Structure ARRAYOFSCISTATUSLLV

WSSTRUCT PORTALLICENCIADO_ARRAYOFSCISTATUSLLV
	WSDATA   oWSSCISTATUSLLV           AS PORTALLICENCIADO_SCISTATUSLLV OPTIONAL
	WSMETHOD NEW
	WSMETHOD INIT
	WSMETHOD CLONE
	WSMETHOD SOAPRECV
ENDWSSTRUCT

WSMETHOD NEW WSCLIENT PORTALLICENCIADO_ARRAYOFSCISTATUSLLV
	::Init()
Return Self

WSMETHOD INIT WSCLIENT PORTALLICENCIADO_ARRAYOFSCISTATUSLLV
	::oWSSCISTATUSLLV      := {} // Array Of  PORTALLICENCIADO_SCISTATUSLLV():New()
Return

WSMETHOD CLONE WSCLIENT PORTALLICENCIADO_ARRAYOFSCISTATUSLLV
	Local oClone := PORTALLICENCIADO_ARRAYOFSCISTATUSLLV():NEW()
	oClone:oWSSCISTATUSLLV := NIL
	If ::oWSSCISTATUSLLV <> NIL 
		oClone:oWSSCISTATUSLLV := {}
		aEval( ::oWSSCISTATUSLLV , { |x| aadd( oClone:oWSSCISTATUSLLV , x:Clone() ) } )
	Endif 
Return oClone

WSMETHOD SOAPRECV WSSEND oResponse WSCLIENT PORTALLICENCIADO_ARRAYOFSCISTATUSLLV
	Local nRElem1, oNodes1, nTElem1
	::Init()
	If oResponse = NIL ; Return ; Endif 
	oNodes1 :=  WSAdvValue( oResponse,"_SCISTATUSLLV","SCISTATUSLLV",{},NIL,.T.,"O",NIL,NIL) 
	nTElem1 := len(oNodes1)
	For nRElem1 := 1 to nTElem1 
		If !WSIsNilNode( oNodes1[nRElem1] )
			aadd(::oWSSCISTATUSLLV , PORTALLICENCIADO_SCISTATUSLLV():New() )
			::oWSSCISTATUSLLV[len(::oWSSCISTATUSLLV)]:SoapRecv(oNodes1[nRElem1])
		Endif
	Next
Return

// WSDL Data Structure ARRAYOFDADOSLANCVENDAS

WSSTRUCT PORTALLICENCIADO_ARRAYOFDADOSLANCVENDAS
	WSDATA   oWSDADOSLANCVENDAS        AS PORTALLICENCIADO_DADOSLANCVENDAS OPTIONAL
	WSMETHOD NEW
	WSMETHOD INIT
	WSMETHOD CLONE
	WSMETHOD SOAPRECV
ENDWSSTRUCT

WSMETHOD NEW WSCLIENT PORTALLICENCIADO_ARRAYOFDADOSLANCVENDAS
	::Init()
Return Self

WSMETHOD INIT WSCLIENT PORTALLICENCIADO_ARRAYOFDADOSLANCVENDAS
	::oWSDADOSLANCVENDAS   := {} // Array Of  PORTALLICENCIADO_DADOSLANCVENDAS():New()
Return

WSMETHOD CLONE WSCLIENT PORTALLICENCIADO_ARRAYOFDADOSLANCVENDAS
	Local oClone := PORTALLICENCIADO_ARRAYOFDADOSLANCVENDAS():NEW()
	oClone:oWSDADOSLANCVENDAS := NIL
	If ::oWSDADOSLANCVENDAS <> NIL 
		oClone:oWSDADOSLANCVENDAS := {}
		aEval( ::oWSDADOSLANCVENDAS , { |x| aadd( oClone:oWSDADOSLANCVENDAS , x:Clone() ) } )
	Endif 
Return oClone

WSMETHOD SOAPRECV WSSEND oResponse WSCLIENT PORTALLICENCIADO_ARRAYOFDADOSLANCVENDAS
	Local nRElem1, oNodes1, nTElem1
	::Init()
	If oResponse = NIL ; Return ; Endif 
	oNodes1 :=  WSAdvValue( oResponse,"_DADOSLANCVENDAS","DADOSLANCVENDAS",{},NIL,.T.,"O",NIL,NIL) 
	nTElem1 := len(oNodes1)
	For nRElem1 := 1 to nTElem1 
		If !WSIsNilNode( oNodes1[nRElem1] )
			aadd(::oWSDADOSLANCVENDAS , PORTALLICENCIADO_DADOSLANCVENDAS():New() )
			::oWSDADOSLANCVENDAS[len(::oWSDADOSLANCVENDAS)]:SoapRecv(oNodes1[nRElem1])
		Endif
	Next
Return

// WSDL Data Structure ARRAYOFSTRUTPRODUTOS

WSSTRUCT PORTALLICENCIADO_ARRAYOFSTRUTPRODUTOS
	WSDATA   oWSSTRUTPRODUTOS          AS PORTALLICENCIADO_STRUTPRODUTOS OPTIONAL
	WSMETHOD NEW
	WSMETHOD INIT
	WSMETHOD CLONE
	WSMETHOD SOAPRECV
ENDWSSTRUCT

WSMETHOD NEW WSCLIENT PORTALLICENCIADO_ARRAYOFSTRUTPRODUTOS
	::Init()
Return Self

WSMETHOD INIT WSCLIENT PORTALLICENCIADO_ARRAYOFSTRUTPRODUTOS
	::oWSSTRUTPRODUTOS     := {} // Array Of  PORTALLICENCIADO_STRUTPRODUTOS():New()
Return

WSMETHOD CLONE WSCLIENT PORTALLICENCIADO_ARRAYOFSTRUTPRODUTOS
	Local oClone := PORTALLICENCIADO_ARRAYOFSTRUTPRODUTOS():NEW()
	oClone:oWSSTRUTPRODUTOS := NIL
	If ::oWSSTRUTPRODUTOS <> NIL 
		oClone:oWSSTRUTPRODUTOS := {}
		aEval( ::oWSSTRUTPRODUTOS , { |x| aadd( oClone:oWSSTRUTPRODUTOS , x:Clone() ) } )
	Endif 
Return oClone

WSMETHOD SOAPRECV WSSEND oResponse WSCLIENT PORTALLICENCIADO_ARRAYOFSTRUTPRODUTOS
	Local nRElem1, oNodes1, nTElem1
	::Init()
	If oResponse = NIL ; Return ; Endif 
	oNodes1 :=  WSAdvValue( oResponse,"_STRUTPRODUTOS","STRUTPRODUTOS",{},NIL,.T.,"O",NIL,NIL) 
	nTElem1 := len(oNodes1)
	For nRElem1 := 1 to nTElem1 
		If !WSIsNilNode( oNodes1[nRElem1] )
			aadd(::oWSSTRUTPRODUTOS , PORTALLICENCIADO_STRUTPRODUTOS():New() )
			::oWSSTRUTPRODUTOS[len(::oWSSTRUTPRODUTOS)]:SoapRecv(oNodes1[nRElem1])
		Endif
	Next
Return

// WSDL Data Structure ARRAYOFDADOSLOGINPORTAL

WSSTRUCT PORTALLICENCIADO_ARRAYOFDADOSLOGINPORTAL
	WSDATA   oWSDADOSLOGINPORTAL       AS PORTALLICENCIADO_DADOSLOGINPORTAL OPTIONAL
	WSMETHOD NEW
	WSMETHOD INIT
	WSMETHOD CLONE
	WSMETHOD SOAPRECV
ENDWSSTRUCT

WSMETHOD NEW WSCLIENT PORTALLICENCIADO_ARRAYOFDADOSLOGINPORTAL
	::Init()
Return Self

WSMETHOD INIT WSCLIENT PORTALLICENCIADO_ARRAYOFDADOSLOGINPORTAL
	::oWSDADOSLOGINPORTAL  := {} // Array Of  PORTALLICENCIADO_DADOSLOGINPORTAL():New()
Return

WSMETHOD CLONE WSCLIENT PORTALLICENCIADO_ARRAYOFDADOSLOGINPORTAL
	Local oClone := PORTALLICENCIADO_ARRAYOFDADOSLOGINPORTAL():NEW()
	oClone:oWSDADOSLOGINPORTAL := NIL
	If ::oWSDADOSLOGINPORTAL <> NIL 
		oClone:oWSDADOSLOGINPORTAL := {}
		aEval( ::oWSDADOSLOGINPORTAL , { |x| aadd( oClone:oWSDADOSLOGINPORTAL , x:Clone() ) } )
	Endif 
Return oClone

WSMETHOD SOAPRECV WSSEND oResponse WSCLIENT PORTALLICENCIADO_ARRAYOFDADOSLOGINPORTAL
	Local nRElem1, oNodes1, nTElem1
	::Init()
	If oResponse = NIL ; Return ; Endif 
	oNodes1 :=  WSAdvValue( oResponse,"_DADOSLOGINPORTAL","DADOSLOGINPORTAL",{},NIL,.T.,"O",NIL,NIL) 
	nTElem1 := len(oNodes1)
	For nRElem1 := 1 to nTElem1 
		If !WSIsNilNode( oNodes1[nRElem1] )
			aadd(::oWSDADOSLOGINPORTAL , PORTALLICENCIADO_DADOSLOGINPORTAL():New() )
			::oWSDADOSLOGINPORTAL[len(::oWSDADOSLOGINPORTAL)]:SoapRecv(oNodes1[nRElem1])
		Endif
	Next
Return

// WSDL Data Structure ARRAYOFLOJASLICENCIADO

WSSTRUCT PORTALLICENCIADO_ARRAYOFLOJASLICENCIADO
	WSDATA   oWSLOJASLICENCIADO        AS PORTALLICENCIADO_LOJASLICENCIADO OPTIONAL
	WSMETHOD NEW
	WSMETHOD INIT
	WSMETHOD CLONE
	WSMETHOD SOAPRECV
ENDWSSTRUCT

WSMETHOD NEW WSCLIENT PORTALLICENCIADO_ARRAYOFLOJASLICENCIADO
	::Init()
Return Self

WSMETHOD INIT WSCLIENT PORTALLICENCIADO_ARRAYOFLOJASLICENCIADO
	::oWSLOJASLICENCIADO   := {} // Array Of  PORTALLICENCIADO_LOJASLICENCIADO():New()
Return

WSMETHOD CLONE WSCLIENT PORTALLICENCIADO_ARRAYOFLOJASLICENCIADO
	Local oClone := PORTALLICENCIADO_ARRAYOFLOJASLICENCIADO():NEW()
	oClone:oWSLOJASLICENCIADO := NIL
	If ::oWSLOJASLICENCIADO <> NIL 
		oClone:oWSLOJASLICENCIADO := {}
		aEval( ::oWSLOJASLICENCIADO , { |x| aadd( oClone:oWSLOJASLICENCIADO , x:Clone() ) } )
	Endif 
Return oClone

WSMETHOD SOAPRECV WSSEND oResponse WSCLIENT PORTALLICENCIADO_ARRAYOFLOJASLICENCIADO
	Local nRElem1, oNodes1, nTElem1
	::Init()
	If oResponse = NIL ; Return ; Endif 
	oNodes1 :=  WSAdvValue( oResponse,"_LOJASLICENCIADO","LOJASLICENCIADO",{},NIL,.T.,"O",NIL,NIL) 
	nTElem1 := len(oNodes1)
	For nRElem1 := 1 to nTElem1 
		If !WSIsNilNode( oNodes1[nRElem1] )
			aadd(::oWSLOJASLICENCIADO , PORTALLICENCIADO_LOJASLICENCIADO():New() )
			::oWSLOJASLICENCIADO[len(::oWSLOJASLICENCIADO)]:SoapRecv(oNodes1[nRElem1])
		Endif
	Next
Return

// WSDL Data Structure ARRAYOFSTRUTPROD

WSSTRUCT PORTALLICENCIADO_ARRAYOFSTRUTPROD
	WSDATA   oWSSTRUTPROD              AS PORTALLICENCIADO_STRUTPROD OPTIONAL
	WSMETHOD NEW
	WSMETHOD INIT
	WSMETHOD CLONE
	WSMETHOD SOAPRECV
ENDWSSTRUCT

WSMETHOD NEW WSCLIENT PORTALLICENCIADO_ARRAYOFSTRUTPROD
	::Init()
Return Self

WSMETHOD INIT WSCLIENT PORTALLICENCIADO_ARRAYOFSTRUTPROD
	::oWSSTRUTPROD         := {} // Array Of  PORTALLICENCIADO_STRUTPROD():New()
Return

WSMETHOD CLONE WSCLIENT PORTALLICENCIADO_ARRAYOFSTRUTPROD
	Local oClone := PORTALLICENCIADO_ARRAYOFSTRUTPROD():NEW()
	oClone:oWSSTRUTPROD := NIL
	If ::oWSSTRUTPROD <> NIL 
		oClone:oWSSTRUTPROD := {}
		aEval( ::oWSSTRUTPROD , { |x| aadd( oClone:oWSSTRUTPROD , x:Clone() ) } )
	Endif 
Return oClone

WSMETHOD SOAPRECV WSSEND oResponse WSCLIENT PORTALLICENCIADO_ARRAYOFSTRUTPROD
	Local nRElem1, oNodes1, nTElem1
	::Init()
	If oResponse = NIL ; Return ; Endif 
	oNodes1 :=  WSAdvValue( oResponse,"_STRUTPROD","STRUTPROD",{},NIL,.T.,"O",NIL,NIL) 
	nTElem1 := len(oNodes1)
	For nRElem1 := 1 to nTElem1 
		If !WSIsNilNode( oNodes1[nRElem1] )
			aadd(::oWSSTRUTPROD , PORTALLICENCIADO_STRUTPROD():New() )
			::oWSSTRUTPROD[len(::oWSSTRUTPROD)]:SoapRecv(oNodes1[nRElem1])
		Endif
	Next
Return

// WSDL Data Structure ARRAYOFSTATUSVISUAL

WSSTRUCT PORTALLICENCIADO_ARRAYOFSTATUSVISUAL
	WSDATA   oWSSTATUSVISUAL           AS PORTALLICENCIADO_STATUSVISUAL OPTIONAL
	WSMETHOD NEW
	WSMETHOD INIT
	WSMETHOD CLONE
	WSMETHOD SOAPRECV
ENDWSSTRUCT

WSMETHOD NEW WSCLIENT PORTALLICENCIADO_ARRAYOFSTATUSVISUAL
	::Init()
Return Self

WSMETHOD INIT WSCLIENT PORTALLICENCIADO_ARRAYOFSTATUSVISUAL
	::oWSSTATUSVISUAL      := {} // Array Of  PORTALLICENCIADO_STATUSVISUAL():New()
Return

WSMETHOD CLONE WSCLIENT PORTALLICENCIADO_ARRAYOFSTATUSVISUAL
	Local oClone := PORTALLICENCIADO_ARRAYOFSTATUSVISUAL():NEW()
	oClone:oWSSTATUSVISUAL := NIL
	If ::oWSSTATUSVISUAL <> NIL 
		oClone:oWSSTATUSVISUAL := {}
		aEval( ::oWSSTATUSVISUAL , { |x| aadd( oClone:oWSSTATUSVISUAL , x:Clone() ) } )
	Endif 
Return oClone

WSMETHOD SOAPRECV WSSEND oResponse WSCLIENT PORTALLICENCIADO_ARRAYOFSTATUSVISUAL
	Local nRElem1, oNodes1, nTElem1
	::Init()
	If oResponse = NIL ; Return ; Endif 
	oNodes1 :=  WSAdvValue( oResponse,"_STATUSVISUAL","STATUSVISUAL",{},NIL,.T.,"O",NIL,NIL) 
	nTElem1 := len(oNodes1)
	For nRElem1 := 1 to nTElem1 
		If !WSIsNilNode( oNodes1[nRElem1] )
			aadd(::oWSSTATUSVISUAL , PORTALLICENCIADO_STATUSVISUAL():New() )
			::oWSSTATUSVISUAL[len(::oWSSTATUSVISUAL)]:SoapRecv(oNodes1[nRElem1])
		Endif
	Next
Return

// WSDL Data Structure ARRAYOFSTRUTVISUALLANC

WSSTRUCT PORTALLICENCIADO_ARRAYOFSTRUTVISUALLANC
	WSDATA   oWSSTRUTVISUALLANC        AS PORTALLICENCIADO_STRUTVISUALLANC OPTIONAL
	WSMETHOD NEW
	WSMETHOD INIT
	WSMETHOD CLONE
	WSMETHOD SOAPRECV
ENDWSSTRUCT

WSMETHOD NEW WSCLIENT PORTALLICENCIADO_ARRAYOFSTRUTVISUALLANC
	::Init()
Return Self

WSMETHOD INIT WSCLIENT PORTALLICENCIADO_ARRAYOFSTRUTVISUALLANC
	::oWSSTRUTVISUALLANC   := {} // Array Of  PORTALLICENCIADO_STRUTVISUALLANC():New()
Return

WSMETHOD CLONE WSCLIENT PORTALLICENCIADO_ARRAYOFSTRUTVISUALLANC
	Local oClone := PORTALLICENCIADO_ARRAYOFSTRUTVISUALLANC():NEW()
	oClone:oWSSTRUTVISUALLANC := NIL
	If ::oWSSTRUTVISUALLANC <> NIL 
		oClone:oWSSTRUTVISUALLANC := {}
		aEval( ::oWSSTRUTVISUALLANC , { |x| aadd( oClone:oWSSTRUTVISUALLANC , x:Clone() ) } )
	Endif 
Return oClone

WSMETHOD SOAPRECV WSSEND oResponse WSCLIENT PORTALLICENCIADO_ARRAYOFSTRUTVISUALLANC
	Local nRElem1, oNodes1, nTElem1
	::Init()
	If oResponse = NIL ; Return ; Endif 
	oNodes1 :=  WSAdvValue( oResponse,"_STRUTVISUALLANC","STRUTVISUALLANC",{},NIL,.T.,"O",NIL,NIL) 
	nTElem1 := len(oNodes1)
	For nRElem1 := 1 to nTElem1 
		If !WSIsNilNode( oNodes1[nRElem1] )
			aadd(::oWSSTRUTVISUALLANC , PORTALLICENCIADO_STRUTVISUALLANC():New() )
			::oWSSTRUTVISUALLANC[len(::oWSSTRUTVISUALLANC)]:SoapRecv(oNodes1[nRElem1])
		Endif
	Next
Return

// WSDL Data Structure SCISTATUS

WSSTRUCT PORTALLICENCIADO_SCISTATUS
	WSDATA   c_LRETORNO                AS string
	WSDATA   cCSCIMSG                  AS string
	WSMETHOD NEW
	WSMETHOD INIT
	WSMETHOD CLONE
	WSMETHOD SOAPRECV
ENDWSSTRUCT

WSMETHOD NEW WSCLIENT PORTALLICENCIADO_SCISTATUS
	::Init()
Return Self

WSMETHOD INIT WSCLIENT PORTALLICENCIADO_SCISTATUS
Return

WSMETHOD CLONE WSCLIENT PORTALLICENCIADO_SCISTATUS
	Local oClone := PORTALLICENCIADO_SCISTATUS():NEW()
	oClone:c_LRETORNO           := ::c_LRETORNO
	oClone:cCSCIMSG             := ::cCSCIMSG
Return oClone

WSMETHOD SOAPRECV WSSEND oResponse WSCLIENT PORTALLICENCIADO_SCISTATUS
	::Init()
	If oResponse = NIL ; Return ; Endif 
	::c_LRETORNO         :=  WSAdvValue( oResponse,"__LRETORNO","string",NIL,"Property c_LRETORNO as s:string on SOAP Response not found.",NIL,"S",NIL,NIL) 
	::cCSCIMSG           :=  WSAdvValue( oResponse,"_CSCIMSG","string",NIL,"Property cCSCIMSG as s:string on SOAP Response not found.",NIL,"S",NIL,NIL) 
Return

// WSDL Data Structure DADOSCONTRATOS

WSSTRUCT PORTALLICENCIADO_DADOSCONTRATOS
	WSDATA   cCCN9_DTFIM               AS string
	WSDATA   cCCN9_DTINIC              AS string
	WSDATA   cCCN9_DTULST              AS string
	WSDATA   cCCN9_NUMERO              AS string
	WSDATA   cCCN9_REVISA              AS string
	WSDATA   cCCN9_SITUAC              AS string
	WSMETHOD NEW
	WSMETHOD INIT
	WSMETHOD CLONE
	WSMETHOD SOAPRECV
ENDWSSTRUCT

WSMETHOD NEW WSCLIENT PORTALLICENCIADO_DADOSCONTRATOS
	::Init()
Return Self

WSMETHOD INIT WSCLIENT PORTALLICENCIADO_DADOSCONTRATOS
Return

WSMETHOD CLONE WSCLIENT PORTALLICENCIADO_DADOSCONTRATOS
	Local oClone := PORTALLICENCIADO_DADOSCONTRATOS():NEW()
	oClone:cCCN9_DTFIM          := ::cCCN9_DTFIM
	oClone:cCCN9_DTINIC         := ::cCCN9_DTINIC
	oClone:cCCN9_DTULST         := ::cCCN9_DTULST
	oClone:cCCN9_NUMERO         := ::cCCN9_NUMERO
	oClone:cCCN9_REVISA         := ::cCCN9_REVISA
	oClone:cCCN9_SITUAC         := ::cCCN9_SITUAC
Return oClone

WSMETHOD SOAPRECV WSSEND oResponse WSCLIENT PORTALLICENCIADO_DADOSCONTRATOS
	::Init()
	If oResponse = NIL ; Return ; Endif 
	::cCCN9_DTFIM        :=  WSAdvValue( oResponse,"_CCN9_DTFIM","string",NIL,"Property cCCN9_DTFIM as s:string on SOAP Response not found.",NIL,"S",NIL,NIL) 
	::cCCN9_DTINIC       :=  WSAdvValue( oResponse,"_CCN9_DTINIC","string",NIL,"Property cCCN9_DTINIC as s:string on SOAP Response not found.",NIL,"S",NIL,NIL) 
	::cCCN9_DTULST       :=  WSAdvValue( oResponse,"_CCN9_DTULST","string",NIL,"Property cCCN9_DTULST as s:string on SOAP Response not found.",NIL,"S",NIL,NIL) 
	::cCCN9_NUMERO       :=  WSAdvValue( oResponse,"_CCN9_NUMERO","string",NIL,"Property cCCN9_NUMERO as s:string on SOAP Response not found.",NIL,"S",NIL,NIL) 
	::cCCN9_REVISA       :=  WSAdvValue( oResponse,"_CCN9_REVISA","string",NIL,"Property cCCN9_REVISA as s:string on SOAP Response not found.",NIL,"S",NIL,NIL) 
	::cCCN9_SITUAC       :=  WSAdvValue( oResponse,"_CCN9_SITUAC","string",NIL,"Property cCCN9_SITUAC as s:string on SOAP Response not found.",NIL,"S",NIL,NIL) 
Return

// WSDL Data Structure STATUSETIQUETA

WSSTRUCT PORTALLICENCIADO_STATUSETIQUETA
	WSDATA   c_LSTATUSETQ              AS string
	WSDATA   cCMSGRETETQ               AS string
	WSMETHOD NEW
	WSMETHOD INIT
	WSMETHOD CLONE
	WSMETHOD SOAPRECV
ENDWSSTRUCT

WSMETHOD NEW WSCLIENT PORTALLICENCIADO_STATUSETIQUETA
	::Init()
Return Self

WSMETHOD INIT WSCLIENT PORTALLICENCIADO_STATUSETIQUETA
Return

WSMETHOD CLONE WSCLIENT PORTALLICENCIADO_STATUSETIQUETA
	Local oClone := PORTALLICENCIADO_STATUSETIQUETA():NEW()
	oClone:c_LSTATUSETQ         := ::c_LSTATUSETQ
	oClone:cCMSGRETETQ          := ::cCMSGRETETQ
Return oClone

WSMETHOD SOAPRECV WSSEND oResponse WSCLIENT PORTALLICENCIADO_STATUSETIQUETA
	::Init()
	If oResponse = NIL ; Return ; Endif 
	::c_LSTATUSETQ       :=  WSAdvValue( oResponse,"__LSTATUSETQ","string",NIL,"Property c_LSTATUSETQ as s:string on SOAP Response not found.",NIL,"S",NIL,NIL) 
	::cCMSGRETETQ        :=  WSAdvValue( oResponse,"_CMSGRETETQ","string",NIL,"Property cCMSGRETETQ as s:string on SOAP Response not found.",NIL,"S",NIL,NIL) 
Return

// WSDL Data Structure STRUTLISTAETQ

WSSTRUCT PORTALLICENCIADO_STRUTLISTAETQ
	WSDATA   cCA2_NOME                 AS string
	WSDATA   cCZ0_CNPJ                 AS string
	WSDATA   cCZ0_DATA                 AS string
	WSDATA   cCZ0_QTDE                 AS string
	WSDATA   cCZ0_STATUS               AS string
	WSMETHOD NEW
	WSMETHOD INIT
	WSMETHOD CLONE
	WSMETHOD SOAPRECV
ENDWSSTRUCT

WSMETHOD NEW WSCLIENT PORTALLICENCIADO_STRUTLISTAETQ
	::Init()
Return Self

WSMETHOD INIT WSCLIENT PORTALLICENCIADO_STRUTLISTAETQ
Return

WSMETHOD CLONE WSCLIENT PORTALLICENCIADO_STRUTLISTAETQ
	Local oClone := PORTALLICENCIADO_STRUTLISTAETQ():NEW()
	oClone:cCA2_NOME            := ::cCA2_NOME
	oClone:cCZ0_CNPJ            := ::cCZ0_CNPJ
	oClone:cCZ0_DATA            := ::cCZ0_DATA
	oClone:cCZ0_QTDE            := ::cCZ0_QTDE
	oClone:cCZ0_STATUS          := ::cCZ0_STATUS
Return oClone

WSMETHOD SOAPRECV WSSEND oResponse WSCLIENT PORTALLICENCIADO_STRUTLISTAETQ
	::Init()
	If oResponse = NIL ; Return ; Endif 
	::cCA2_NOME          :=  WSAdvValue( oResponse,"_CA2_NOME","string",NIL,"Property cCA2_NOME as s:string on SOAP Response not found.",NIL,"S",NIL,NIL) 
	::cCZ0_CNPJ          :=  WSAdvValue( oResponse,"_CZ0_CNPJ","string",NIL,"Property cCZ0_CNPJ as s:string on SOAP Response not found.",NIL,"S",NIL,NIL) 
	::cCZ0_DATA          :=  WSAdvValue( oResponse,"_CZ0_DATA","string",NIL,"Property cCZ0_DATA as s:string on SOAP Response not found.",NIL,"S",NIL,NIL) 
	::cCZ0_QTDE          :=  WSAdvValue( oResponse,"_CZ0_QTDE","string",NIL,"Property cCZ0_QTDE as s:string on SOAP Response not found.",NIL,"S",NIL,NIL) 
	::cCZ0_STATUS        :=  WSAdvValue( oResponse,"_CZ0_STATUS","string",NIL,"Property cCZ0_STATUS as s:string on SOAP Response not found.",NIL,"S",NIL,NIL) 
Return

// WSDL Data Structure SCISTATUSLLV

WSSTRUCT PORTALLICENCIADO_SCISTATUSLLV
	WSDATA   c_LRETORNO                AS string
	WSDATA   cCSCIMSG                  AS string
	WSMETHOD NEW
	WSMETHOD INIT
	WSMETHOD CLONE
	WSMETHOD SOAPRECV
ENDWSSTRUCT

WSMETHOD NEW WSCLIENT PORTALLICENCIADO_SCISTATUSLLV
	::Init()
Return Self

WSMETHOD INIT WSCLIENT PORTALLICENCIADO_SCISTATUSLLV
Return

WSMETHOD CLONE WSCLIENT PORTALLICENCIADO_SCISTATUSLLV
	Local oClone := PORTALLICENCIADO_SCISTATUSLLV():NEW()
	oClone:c_LRETORNO           := ::c_LRETORNO
	oClone:cCSCIMSG             := ::cCSCIMSG
Return oClone

WSMETHOD SOAPRECV WSSEND oResponse WSCLIENT PORTALLICENCIADO_SCISTATUSLLV
	::Init()
	If oResponse = NIL ; Return ; Endif 
	::c_LRETORNO         :=  WSAdvValue( oResponse,"__LRETORNO","string",NIL,"Property c_LRETORNO as s:string on SOAP Response not found.",NIL,"S",NIL,NIL) 
	::cCSCIMSG           :=  WSAdvValue( oResponse,"_CSCIMSG","string",NIL,"Property cCSCIMSG as s:string on SOAP Response not found.",NIL,"S",NIL,NIL) 
Return

// WSDL Data Structure DADOSLANCVENDAS

WSSTRUCT PORTALLICENCIADO_DADOSLANCVENDAS
	WSDATA   cCZ9_DTFIMPER             AS string
	WSDATA   cCZ9_DTINIPER             AS string
	WSDATA   cCZ9_NUM                  AS string
	WSDATA   cCZ9_NUMBCO               AS string
	WSDATA   cCZ9_NUMCTO               AS string
	WSDATA   cCZ9_PARCELA              AS string
	WSDATA   cCZ9_PERIODO              AS string
	WSDATA   cCZ9_PORTADO              AS string
	WSDATA   cCZ9_PREFIXO              AS string
	WSDATA   cCZ9_QUANT                AS string
	WSDATA   cCZ9_REVCTO               AS string
	WSDATA   cCZ9_STATUS               AS string
	WSDATA   cCZ9_TIPO                 AS string
	WSDATA   cCZ9_VALOR                AS string
	WSDATA   cCZ9_VLRLIQ               AS string
	WSMETHOD NEW
	WSMETHOD INIT
	WSMETHOD CLONE
	WSMETHOD SOAPRECV
ENDWSSTRUCT

WSMETHOD NEW WSCLIENT PORTALLICENCIADO_DADOSLANCVENDAS
	::Init()
Return Self

WSMETHOD INIT WSCLIENT PORTALLICENCIADO_DADOSLANCVENDAS
Return

WSMETHOD CLONE WSCLIENT PORTALLICENCIADO_DADOSLANCVENDAS
	Local oClone := PORTALLICENCIADO_DADOSLANCVENDAS():NEW()
	oClone:cCZ9_DTFIMPER        := ::cCZ9_DTFIMPER
	oClone:cCZ9_DTINIPER        := ::cCZ9_DTINIPER
	oClone:cCZ9_NUM             := ::cCZ9_NUM
	oClone:cCZ9_NUMBCO          := ::cCZ9_NUMBCO
	oClone:cCZ9_NUMCTO          := ::cCZ9_NUMCTO
	oClone:cCZ9_PARCELA         := ::cCZ9_PARCELA
	oClone:cCZ9_PERIODO         := ::cCZ9_PERIODO
	oClone:cCZ9_PORTADO         := ::cCZ9_PORTADO
	oClone:cCZ9_PREFIXO         := ::cCZ9_PREFIXO
	oClone:cCZ9_QUANT           := ::cCZ9_QUANT
	oClone:cCZ9_REVCTO          := ::cCZ9_REVCTO
	oClone:cCZ9_STATUS          := ::cCZ9_STATUS
	oClone:cCZ9_TIPO            := ::cCZ9_TIPO
	oClone:cCZ9_VALOR           := ::cCZ9_VALOR
	oClone:cCZ9_VLRLIQ          := ::cCZ9_VLRLIQ
Return oClone

WSMETHOD SOAPRECV WSSEND oResponse WSCLIENT PORTALLICENCIADO_DADOSLANCVENDAS
	::Init()
	If oResponse = NIL ; Return ; Endif 
	::cCZ9_DTFIMPER      :=  WSAdvValue( oResponse,"_CZ9_DTFIMPER","string",NIL,"Property cCZ9_DTFIMPER as s:string on SOAP Response not found.",NIL,"S",NIL,NIL) 
	::cCZ9_DTINIPER      :=  WSAdvValue( oResponse,"_CZ9_DTINIPER","string",NIL,"Property cCZ9_DTINIPER as s:string on SOAP Response not found.",NIL,"S",NIL,NIL) 
	::cCZ9_NUM           :=  WSAdvValue( oResponse,"_CZ9_NUM","string",NIL,"Property cCZ9_NUM as s:string on SOAP Response not found.",NIL,"S",NIL,NIL) 
	::cCZ9_NUMBCO        :=  WSAdvValue( oResponse,"_CZ9_NUMBCO","string",NIL,"Property cCZ9_NUMBCO as s:string on SOAP Response not found.",NIL,"S",NIL,NIL) 
	::cCZ9_NUMCTO        :=  WSAdvValue( oResponse,"_CZ9_NUMCTO","string",NIL,"Property cCZ9_NUMCTO as s:string on SOAP Response not found.",NIL,"S",NIL,NIL) 
	::cCZ9_PARCELA       :=  WSAdvValue( oResponse,"_CZ9_PARCELA","string",NIL,"Property cCZ9_PARCELA as s:string on SOAP Response not found.",NIL,"S",NIL,NIL) 
	::cCZ9_PERIODO       :=  WSAdvValue( oResponse,"_CZ9_PERIODO","string",NIL,"Property cCZ9_PERIODO as s:string on SOAP Response not found.",NIL,"S",NIL,NIL) 
	::cCZ9_PORTADO       :=  WSAdvValue( oResponse,"_CZ9_PORTADO","string",NIL,"Property cCZ9_PORTADO as s:string on SOAP Response not found.",NIL,"S",NIL,NIL) 
	::cCZ9_PREFIXO       :=  WSAdvValue( oResponse,"_CZ9_PREFIXO","string",NIL,"Property cCZ9_PREFIXO as s:string on SOAP Response not found.",NIL,"S",NIL,NIL) 
	::cCZ9_QUANT         :=  WSAdvValue( oResponse,"_CZ9_QUANT","string",NIL,"Property cCZ9_QUANT as s:string on SOAP Response not found.",NIL,"S",NIL,NIL) 
	::cCZ9_REVCTO        :=  WSAdvValue( oResponse,"_CZ9_REVCTO","string",NIL,"Property cCZ9_REVCTO as s:string on SOAP Response not found.",NIL,"S",NIL,NIL) 
	::cCZ9_STATUS        :=  WSAdvValue( oResponse,"_CZ9_STATUS","string",NIL,"Property cCZ9_STATUS as s:string on SOAP Response not found.",NIL,"S",NIL,NIL) 
	::cCZ9_TIPO          :=  WSAdvValue( oResponse,"_CZ9_TIPO","string",NIL,"Property cCZ9_TIPO as s:string on SOAP Response not found.",NIL,"S",NIL,NIL) 
	::cCZ9_VALOR         :=  WSAdvValue( oResponse,"_CZ9_VALOR","string",NIL,"Property cCZ9_VALOR as s:string on SOAP Response not found.",NIL,"S",NIL,NIL) 
	::cCZ9_VLRLIQ        :=  WSAdvValue( oResponse,"_CZ9_VLRLIQ","string",NIL,"Property cCZ9_VLRLIQ as s:string on SOAP Response not found.",NIL,"S",NIL,NIL) 
Return

// WSDL Data Structure STRUTPRODUTOS

WSSTRUCT PORTALLICENCIADO_STRUTPRODUTOS
	WSDATA   c_LRETORNO                AS string
	WSDATA   cCB1_DESC                 AS string
	WSDATA   cCRETMSG                  AS string
	WSDATA   cCZC_CODLIC               AS string
	WSDATA   cCZC_CODPRO               AS string
	WSDATA   cCZC_LOJLIC               AS string
	WSDATA   cCZC_NUMCTO               AS string
	WSDATA   cCZC_QUANT                AS string
	WSDATA   cCZC_REVISA               AS string
	WSDATA   cCZC_VALOR                AS string
	WSDATA   cCZC_VLRLIQ               AS string
	WSMETHOD NEW
	WSMETHOD INIT
	WSMETHOD CLONE
	WSMETHOD SOAPRECV
ENDWSSTRUCT

WSMETHOD NEW WSCLIENT PORTALLICENCIADO_STRUTPRODUTOS
	::Init()
Return Self

WSMETHOD INIT WSCLIENT PORTALLICENCIADO_STRUTPRODUTOS
Return

WSMETHOD CLONE WSCLIENT PORTALLICENCIADO_STRUTPRODUTOS
	Local oClone := PORTALLICENCIADO_STRUTPRODUTOS():NEW()
	oClone:c_LRETORNO           := ::c_LRETORNO
	oClone:cCB1_DESC            := ::cCB1_DESC
	oClone:cCRETMSG             := ::cCRETMSG
	oClone:cCZC_CODLIC          := ::cCZC_CODLIC
	oClone:cCZC_CODPRO          := ::cCZC_CODPRO
	oClone:cCZC_LOJLIC          := ::cCZC_LOJLIC
	oClone:cCZC_NUMCTO          := ::cCZC_NUMCTO
	oClone:cCZC_QUANT           := ::cCZC_QUANT
	oClone:cCZC_REVISA          := ::cCZC_REVISA
	oClone:cCZC_VALOR           := ::cCZC_VALOR
	oClone:cCZC_VLRLIQ          := ::cCZC_VLRLIQ
Return oClone

WSMETHOD SOAPRECV WSSEND oResponse WSCLIENT PORTALLICENCIADO_STRUTPRODUTOS
	::Init()
	If oResponse = NIL ; Return ; Endif 
	::c_LRETORNO         :=  WSAdvValue( oResponse,"__LRETORNO","string",NIL,"Property c_LRETORNO as s:string on SOAP Response not found.",NIL,"S",NIL,NIL) 
	::cCB1_DESC          :=  WSAdvValue( oResponse,"_CB1_DESC","string",NIL,"Property cCB1_DESC as s:string on SOAP Response not found.",NIL,"S",NIL,NIL) 
	::cCRETMSG           :=  WSAdvValue( oResponse,"_CRETMSG","string",NIL,"Property cCRETMSG as s:string on SOAP Response not found.",NIL,"S",NIL,NIL) 
	::cCZC_CODLIC        :=  WSAdvValue( oResponse,"_CZC_CODLIC","string",NIL,"Property cCZC_CODLIC as s:string on SOAP Response not found.",NIL,"S",NIL,NIL) 
	::cCZC_CODPRO        :=  WSAdvValue( oResponse,"_CZC_CODPRO","string",NIL,"Property cCZC_CODPRO as s:string on SOAP Response not found.",NIL,"S",NIL,NIL) 
	::cCZC_LOJLIC        :=  WSAdvValue( oResponse,"_CZC_LOJLIC","string",NIL,"Property cCZC_LOJLIC as s:string on SOAP Response not found.",NIL,"S",NIL,NIL) 
	::cCZC_NUMCTO        :=  WSAdvValue( oResponse,"_CZC_NUMCTO","string",NIL,"Property cCZC_NUMCTO as s:string on SOAP Response not found.",NIL,"S",NIL,NIL) 
	::cCZC_QUANT         :=  WSAdvValue( oResponse,"_CZC_QUANT","string",NIL,"Property cCZC_QUANT as s:string on SOAP Response not found.",NIL,"S",NIL,NIL) 
	::cCZC_REVISA        :=  WSAdvValue( oResponse,"_CZC_REVISA","string",NIL,"Property cCZC_REVISA as s:string on SOAP Response not found.",NIL,"S",NIL,NIL) 
	::cCZC_VALOR         :=  WSAdvValue( oResponse,"_CZC_VALOR","string",NIL,"Property cCZC_VALOR as s:string on SOAP Response not found.",NIL,"S",NIL,NIL) 
	::cCZC_VLRLIQ        :=  WSAdvValue( oResponse,"_CZC_VLRLIQ","string",NIL,"Property cCZC_VLRLIQ as s:string on SOAP Response not found.",NIL,"S",NIL,NIL) 
Return

// WSDL Data Structure DADOSLOGINPORTAL

WSSTRUCT PORTALLICENCIADO_DADOSLOGINPORTAL
	WSDATA   c_CLOGINSCI               AS string
	WSDATA   c_CRETMSN                 AS string
	WSDATA   cCCLIFOR                  AS string
	WSDATA   cCCODCGC                  AS string
	WSDATA   cCCODLOJA                 AS string
	WSDATA   cCNOMREDUZ                AS string
	WSMETHOD NEW
	WSMETHOD INIT
	WSMETHOD CLONE
	WSMETHOD SOAPRECV
ENDWSSTRUCT

WSMETHOD NEW WSCLIENT PORTALLICENCIADO_DADOSLOGINPORTAL
	::Init()
Return Self

WSMETHOD INIT WSCLIENT PORTALLICENCIADO_DADOSLOGINPORTAL
Return

WSMETHOD CLONE WSCLIENT PORTALLICENCIADO_DADOSLOGINPORTAL
	Local oClone := PORTALLICENCIADO_DADOSLOGINPORTAL():NEW()
	oClone:c_CLOGINSCI          := ::c_CLOGINSCI
	oClone:c_CRETMSN            := ::c_CRETMSN
	oClone:cCCLIFOR             := ::cCCLIFOR
	oClone:cCCODCGC             := ::cCCODCGC
	oClone:cCCODLOJA            := ::cCCODLOJA
	oClone:cCNOMREDUZ           := ::cCNOMREDUZ
Return oClone

WSMETHOD SOAPRECV WSSEND oResponse WSCLIENT PORTALLICENCIADO_DADOSLOGINPORTAL
	::Init()
	If oResponse = NIL ; Return ; Endif 
	::c_CLOGINSCI        :=  WSAdvValue( oResponse,"__CLOGINSCI","string",NIL,"Property c_CLOGINSCI as s:string on SOAP Response not found.",NIL,"S",NIL,NIL) 
	::c_CRETMSN          :=  WSAdvValue( oResponse,"__CRETMSN","string",NIL,"Property c_CRETMSN as s:string on SOAP Response not found.",NIL,"S",NIL,NIL) 
	::cCCLIFOR           :=  WSAdvValue( oResponse,"_CCLIFOR","string",NIL,"Property cCCLIFOR as s:string on SOAP Response not found.",NIL,"S",NIL,NIL) 
	::cCCODCGC           :=  WSAdvValue( oResponse,"_CCODCGC","string",NIL,"Property cCCODCGC as s:string on SOAP Response not found.",NIL,"S",NIL,NIL) 
	::cCCODLOJA          :=  WSAdvValue( oResponse,"_CCODLOJA","string",NIL,"Property cCCODLOJA as s:string on SOAP Response not found.",NIL,"S",NIL,NIL) 
	::cCNOMREDUZ         :=  WSAdvValue( oResponse,"_CNOMREDUZ","string",NIL,"Property cCNOMREDUZ as s:string on SOAP Response not found.",NIL,"S",NIL,NIL) 
Return

// WSDL Data Structure LOJASLICENCIADO

WSSTRUCT PORTALLICENCIADO_LOJASLICENCIADO
	WSDATA   cCCGCLOJA                 AS string
	WSDATA   cCCODLOJA                 AS string
	WSDATA   cCDESCLOJA                AS string
	WSMETHOD NEW
	WSMETHOD INIT
	WSMETHOD CLONE
	WSMETHOD SOAPRECV
ENDWSSTRUCT

WSMETHOD NEW WSCLIENT PORTALLICENCIADO_LOJASLICENCIADO
	::Init()
Return Self

WSMETHOD INIT WSCLIENT PORTALLICENCIADO_LOJASLICENCIADO
Return

WSMETHOD CLONE WSCLIENT PORTALLICENCIADO_LOJASLICENCIADO
	Local oClone := PORTALLICENCIADO_LOJASLICENCIADO():NEW()
	oClone:cCCGCLOJA            := ::cCCGCLOJA
	oClone:cCCODLOJA            := ::cCCODLOJA
	oClone:cCDESCLOJA           := ::cCDESCLOJA
Return oClone

WSMETHOD SOAPRECV WSSEND oResponse WSCLIENT PORTALLICENCIADO_LOJASLICENCIADO
	::Init()
	If oResponse = NIL ; Return ; Endif 
	::cCCGCLOJA          :=  WSAdvValue( oResponse,"_CCGCLOJA","string",NIL,"Property cCCGCLOJA as s:string on SOAP Response not found.",NIL,"S",NIL,NIL) 
	::cCCODLOJA          :=  WSAdvValue( oResponse,"_CCODLOJA","string",NIL,"Property cCCODLOJA as s:string on SOAP Response not found.",NIL,"S",NIL,NIL) 
	::cCDESCLOJA         :=  WSAdvValue( oResponse,"_CDESCLOJA","string",NIL,"Property cCDESCLOJA as s:string on SOAP Response not found.",NIL,"S",NIL,NIL) 
Return

// WSDL Data Structure STRUTPROD

WSSTRUCT PORTALLICENCIADO_STRUTPROD
	WSDATA   c_LRET                    AS string
	WSDATA   cCSTATMSG                 AS string
	WSDATA   cCZ9_DTFIMPER             AS string
	WSDATA   cCZ9_DTINIPER             AS string
	WSDATA   cCZ9_PERIODO              AS string
	WSDATA   cCZA_CODPDV               AS string
	WSDATA   cCZC_CODLIC               AS string
	WSDATA   cCZC_CODPRO               AS string
	WSDATA   cCZC_LOJLIC               AS string
	WSDATA   cCZC_NUMCTO               AS string
	WSDATA   cCZC_QUANT                AS string
	WSDATA   cCZC_REVISA               AS string
	WSDATA   cCZC_VALOR                AS string
	WSDATA   cCZC_VLRLIQ               AS string
	WSMETHOD NEW
	WSMETHOD INIT
	WSMETHOD CLONE
	WSMETHOD SOAPRECV
ENDWSSTRUCT

WSMETHOD NEW WSCLIENT PORTALLICENCIADO_STRUTPROD
	::Init()
Return Self

WSMETHOD INIT WSCLIENT PORTALLICENCIADO_STRUTPROD
Return

WSMETHOD CLONE WSCLIENT PORTALLICENCIADO_STRUTPROD
	Local oClone := PORTALLICENCIADO_STRUTPROD():NEW()
	oClone:c_LRET               := ::c_LRET
	oClone:cCSTATMSG            := ::cCSTATMSG
	oClone:cCZ9_DTFIMPER        := ::cCZ9_DTFIMPER
	oClone:cCZ9_DTINIPER        := ::cCZ9_DTINIPER
	oClone:cCZ9_PERIODO         := ::cCZ9_PERIODO
	oClone:cCZA_CODPDV          := ::cCZA_CODPDV
	oClone:cCZC_CODLIC          := ::cCZC_CODLIC
	oClone:cCZC_CODPRO          := ::cCZC_CODPRO
	oClone:cCZC_LOJLIC          := ::cCZC_LOJLIC
	oClone:cCZC_NUMCTO          := ::cCZC_NUMCTO
	oClone:cCZC_QUANT           := ::cCZC_QUANT
	oClone:cCZC_REVISA          := ::cCZC_REVISA
	oClone:cCZC_VALOR           := ::cCZC_VALOR
	oClone:cCZC_VLRLIQ          := ::cCZC_VLRLIQ
Return oClone

WSMETHOD SOAPRECV WSSEND oResponse WSCLIENT PORTALLICENCIADO_STRUTPROD
	::Init()
	If oResponse = NIL ; Return ; Endif 
	::c_LRET             :=  WSAdvValue( oResponse,"__LRET","string",NIL,"Property c_LRET as s:string on SOAP Response not found.",NIL,"S",NIL,NIL) 
	::cCSTATMSG          :=  WSAdvValue( oResponse,"_CSTATMSG","string",NIL,"Property cCSTATMSG as s:string on SOAP Response not found.",NIL,"S",NIL,NIL) 
	::cCZ9_DTFIMPER      :=  WSAdvValue( oResponse,"_CZ9_DTFIMPER","string",NIL,"Property cCZ9_DTFIMPER as s:string on SOAP Response not found.",NIL,"S",NIL,NIL) 
	::cCZ9_DTINIPER      :=  WSAdvValue( oResponse,"_CZ9_DTINIPER","string",NIL,"Property cCZ9_DTINIPER as s:string on SOAP Response not found.",NIL,"S",NIL,NIL) 
	::cCZ9_PERIODO       :=  WSAdvValue( oResponse,"_CZ9_PERIODO","string",NIL,"Property cCZ9_PERIODO as s:string on SOAP Response not found.",NIL,"S",NIL,NIL) 
	::cCZA_CODPDV        :=  WSAdvValue( oResponse,"_CZA_CODPDV","string",NIL,"Property cCZA_CODPDV as s:string on SOAP Response not found.",NIL,"S",NIL,NIL) 
	::cCZC_CODLIC        :=  WSAdvValue( oResponse,"_CZC_CODLIC","string",NIL,"Property cCZC_CODLIC as s:string on SOAP Response not found.",NIL,"S",NIL,NIL) 
	::cCZC_CODPRO        :=  WSAdvValue( oResponse,"_CZC_CODPRO","string",NIL,"Property cCZC_CODPRO as s:string on SOAP Response not found.",NIL,"S",NIL,NIL) 
	::cCZC_LOJLIC        :=  WSAdvValue( oResponse,"_CZC_LOJLIC","string",NIL,"Property cCZC_LOJLIC as s:string on SOAP Response not found.",NIL,"S",NIL,NIL) 
	::cCZC_NUMCTO        :=  WSAdvValue( oResponse,"_CZC_NUMCTO","string",NIL,"Property cCZC_NUMCTO as s:string on SOAP Response not found.",NIL,"S",NIL,NIL) 
	::cCZC_QUANT         :=  WSAdvValue( oResponse,"_CZC_QUANT","string",NIL,"Property cCZC_QUANT as s:string on SOAP Response not found.",NIL,"S",NIL,NIL) 
	::cCZC_REVISA        :=  WSAdvValue( oResponse,"_CZC_REVISA","string",NIL,"Property cCZC_REVISA as s:string on SOAP Response not found.",NIL,"S",NIL,NIL) 
	::cCZC_VALOR         :=  WSAdvValue( oResponse,"_CZC_VALOR","string",NIL,"Property cCZC_VALOR as s:string on SOAP Response not found.",NIL,"S",NIL,NIL) 
	::cCZC_VLRLIQ        :=  WSAdvValue( oResponse,"_CZC_VLRLIQ","string",NIL,"Property cCZC_VLRLIQ as s:string on SOAP Response not found.",NIL,"S",NIL,NIL) 
Return

// WSDL Data Structure STATUSVISUAL

WSSTRUCT PORTALLICENCIADO_STATUSVISUAL
	WSDATA   c_LSTATUSVIS              AS string
	WSDATA   cCMSGRETVIS               AS string
	WSMETHOD NEW
	WSMETHOD INIT
	WSMETHOD CLONE
	WSMETHOD SOAPRECV
ENDWSSTRUCT

WSMETHOD NEW WSCLIENT PORTALLICENCIADO_STATUSVISUAL
	::Init()
Return Self

WSMETHOD INIT WSCLIENT PORTALLICENCIADO_STATUSVISUAL
Return

WSMETHOD CLONE WSCLIENT PORTALLICENCIADO_STATUSVISUAL
	Local oClone := PORTALLICENCIADO_STATUSVISUAL():NEW()
	oClone:c_LSTATUSVIS         := ::c_LSTATUSVIS
	oClone:cCMSGRETVIS          := ::cCMSGRETVIS
Return oClone

WSMETHOD SOAPRECV WSSEND oResponse WSCLIENT PORTALLICENCIADO_STATUSVISUAL
	::Init()
	If oResponse = NIL ; Return ; Endif 
	::c_LSTATUSVIS       :=  WSAdvValue( oResponse,"__LSTATUSVIS","string",NIL,"Property c_LSTATUSVIS as s:string on SOAP Response not found.",NIL,"S",NIL,NIL) 
	::cCMSGRETVIS        :=  WSAdvValue( oResponse,"_CMSGRETVIS","string",NIL,"Property cCMSGRETVIS as s:string on SOAP Response not found.",NIL,"S",NIL,NIL) 
Return

// WSDL Data Structure STRUTVISUALLANC

WSSTRUCT PORTALLICENCIADO_STRUTVISUALLANC
	WSDATA   cCZ9_CODCLI               AS string
	WSDATA   cCZ9_DTFIMPE              AS string
	WSDATA   cCZ9_DTINIPE              AS string
	WSDATA   cCZ9_LOJCLI               AS string
	WSDATA   cCZ9_NUMCTO               AS string
	WSDATA   cCZ9_PERIODO              AS string
	WSDATA   cCZ9_QUANT                AS string
	WSDATA   cCZ9_REVCTO               AS string
	WSDATA   cCZ9_STATUS               AS string
	WSDATA   cCZ9_VALOR                AS string
	WSDATA   cCZ9_VLRLIQ               AS string
	WSMETHOD NEW
	WSMETHOD INIT
	WSMETHOD CLONE
	WSMETHOD SOAPRECV
ENDWSSTRUCT

WSMETHOD NEW WSCLIENT PORTALLICENCIADO_STRUTVISUALLANC
	::Init()
Return Self

WSMETHOD INIT WSCLIENT PORTALLICENCIADO_STRUTVISUALLANC
Return

WSMETHOD CLONE WSCLIENT PORTALLICENCIADO_STRUTVISUALLANC
	Local oClone := PORTALLICENCIADO_STRUTVISUALLANC():NEW()
	oClone:cCZ9_CODCLI          := ::cCZ9_CODCLI
	oClone:cCZ9_DTFIMPE         := ::cCZ9_DTFIMPE
	oClone:cCZ9_DTINIPE         := ::cCZ9_DTINIPE
	oClone:cCZ9_LOJCLI          := ::cCZ9_LOJCLI
	oClone:cCZ9_NUMCTO          := ::cCZ9_NUMCTO
	oClone:cCZ9_PERIODO         := ::cCZ9_PERIODO
	oClone:cCZ9_QUANT           := ::cCZ9_QUANT
	oClone:cCZ9_REVCTO          := ::cCZ9_REVCTO
	oClone:cCZ9_STATUS          := ::cCZ9_STATUS
	oClone:cCZ9_VALOR           := ::cCZ9_VALOR
	oClone:cCZ9_VLRLIQ          := ::cCZ9_VLRLIQ
Return oClone

WSMETHOD SOAPRECV WSSEND oResponse WSCLIENT PORTALLICENCIADO_STRUTVISUALLANC
	::Init()
	If oResponse = NIL ; Return ; Endif 
	::cCZ9_CODCLI        :=  WSAdvValue( oResponse,"_CZ9_CODCLI","string",NIL,"Property cCZ9_CODCLI as s:string on SOAP Response not found.",NIL,"S",NIL,NIL) 
	::cCZ9_DTFIMPE       :=  WSAdvValue( oResponse,"_CZ9_DTFIMPE","string",NIL,"Property cCZ9_DTFIMPE as s:string on SOAP Response not found.",NIL,"S",NIL,NIL) 
	::cCZ9_DTINIPE       :=  WSAdvValue( oResponse,"_CZ9_DTINIPE","string",NIL,"Property cCZ9_DTINIPE as s:string on SOAP Response not found.",NIL,"S",NIL,NIL) 
	::cCZ9_LOJCLI        :=  WSAdvValue( oResponse,"_CZ9_LOJCLI","string",NIL,"Property cCZ9_LOJCLI as s:string on SOAP Response not found.",NIL,"S",NIL,NIL) 
	::cCZ9_NUMCTO        :=  WSAdvValue( oResponse,"_CZ9_NUMCTO","string",NIL,"Property cCZ9_NUMCTO as s:string on SOAP Response not found.",NIL,"S",NIL,NIL) 
	::cCZ9_PERIODO       :=  WSAdvValue( oResponse,"_CZ9_PERIODO","string",NIL,"Property cCZ9_PERIODO as s:string on SOAP Response not found.",NIL,"S",NIL,NIL) 
	::cCZ9_QUANT         :=  WSAdvValue( oResponse,"_CZ9_QUANT","string",NIL,"Property cCZ9_QUANT as s:string on SOAP Response not found.",NIL,"S",NIL,NIL) 
	::cCZ9_REVCTO        :=  WSAdvValue( oResponse,"_CZ9_REVCTO","string",NIL,"Property cCZ9_REVCTO as s:string on SOAP Response not found.",NIL,"S",NIL,NIL) 
	::cCZ9_STATUS        :=  WSAdvValue( oResponse,"_CZ9_STATUS","string",NIL,"Property cCZ9_STATUS as s:string on SOAP Response not found.",NIL,"S",NIL,NIL) 
	::cCZ9_VALOR         :=  WSAdvValue( oResponse,"_CZ9_VALOR","string",NIL,"Property cCZ9_VALOR as s:string on SOAP Response not found.",NIL,"S",NIL,NIL) 
	::cCZ9_VLRLIQ        :=  WSAdvValue( oResponse,"_CZ9_VLRLIQ","string",NIL,"Property cCZ9_VLRLIQ as s:string on SOAP Response not found.",NIL,"S",NIL,NIL) 
Return