SELECT DISTINCT SA1.A1_COD
FROM SE1990 SE1
INNER JOIN SA1990 SA1
    ON SE1.E1_CLIENTE = SA1.A1_COD
    AND SE1.E1_LOJA = SA1.A1_LOJA
    AND (
        (SA1.A1_XDTIRES = '' OR GETDATE() < SA1.A1_XDTIRES)
    )
    AND (
        (SA1.A1_XDTFRES = '' OR GETDATE() > SA1.A1_XDTFRES)
    )
    AND SA1.D_E_L_E_T_ = ''
WHERE SE1.D_E_L_E_T_ = ''
  AND SE1.E1_VENCREA < GETDATE()
  AND SE1.E1_BAIXA = ''
