SELECT DISTINCT SA1.A1_SPM
     , SE1.*
FROM SE1
INNER JOIN SA1
    ON SE1.E1_FORNECE = SA1.A1_COD
    AND SE1.E1_LOJA = SA1.A1_LOJA
WHERE SE1.E1_VENCTO < GETDATE()

SELECT DISTINCT SA1.A1_SPM,
       SE1.*
FROM SE1
INNER JOIN SA1
    ON SE1.E1_FORNECE = SA1.A1_COD
   AND SE1.E1_LOJA = SA1.A1_LOJA
WHERE SE1.E1_VENCTO < SYSDATE