#ifdef SPANISH
	#define STR0001 "Emite un detalle para control de las solicitudes registradas,"
	#define STR0002 "sus respectivos pedidos y plazos de entrega."
	#define STR0003 " Por Solicitud      "
	#define STR0004 " Por Producto       "
	#define STR0005 "Detalle de Solicitudes de Compras"
	#define STR0006 "A Rayas"
	#define STR0007 "Administracion "
	#define STR0008 "REGISTRO(S)"
	#define STR0009 "DETALLE DE SOLICITUDES DE COMPRAS"
	#define STR0010 " (Incluyendo Pedidos de Compra)"
	#define STR0011 "NUMERO ITEM PRODUC.         D E S C R I P C.               TP GRUP    CANTIDAD  UM               CENTRO EMISION    ENTREGA    SOLICITANTE  DT.LIMITE         SALDO N.PED/ CODIGO LJ RAZON SOCIAL                  DE FCH. "
	#define STR0012 "                                                                     SOLICITADA                   COSTO            DE S.C.                 DE COMPRA       DE S.C. N.COT. PROV.                                   EMISION "
	#define STR0013 "Seleccionando Registros..."
	#define STR0014 "ANULADO POR EL OPERADOR"
	#define STR0015 "Total  -  "
	#define STR0016 "Pedidos generados por cotizacion num."
	#define STR0017 "NUMERO ITEM PRODUC.         D E S C R I P C.               TP GRUP    CANTIDAD  UM               CENTRO EMISION    ENTREGA    SOLICITANTE  FCHLIMITE         SALDO        CODIGO LJ RAZON SOCIAL                        "
	#define STR0018 "                                                                     SOLICITADA                   COSTO            DE S.C.                 DE COMPRA       DE S.C.        PROV.                                         "
	#define STR0019 "Fc.Limite"
	#define STR0020 "Saldo SC"
	#define STR0021 "ANULADA POR EL SISTEMA."
	#define STR0022 "Solicitudes de Compra"
	#define STR0023 "de Compra"
	#define STR0024 "Numero"
	#define STR0025 "SC"
	#define STR0026 "Item"
	#define STR0027 "Tp"
	#define STR0028 "UM"
	#define STR0029 "Fech.de"
	#define STR0030 "Emision"
	#define STR0031 "Entrega"
	#define STR0032 "Numero"
	#define STR0033 "PC"
	#define STR0034 "Provee."
	#define STR0035 "Td"
#else
	#ifdef ENGLISH
		#define STR0001 "It prints a list for registered requisitions control, "
		#define STR0002 "their respective orders and delivery terms.        "
		#define STR0003 " By Request   "
		#define STR0004 " By Product        "
		#define STR0005 "List of Purchase Requisitions   "
		#define STR0006 "Z.Form "
		#define STR0007 "Management   "
		#define STR0008 "RECORD(S)  "
		#define STR0009 "LIST OF PURCHASE REQUESTS     "
		#define STR0010 " (Including Purchase Orders)  "
		#define STR0011 "NUMBER ITEM PRODUCT         D E S C R I P T.               TP GRP    QUANTITY   UM               CENTER ISSUE      DELIV.     PETITIONER   DEADLINE          BLNCE N.REQ/ CODE   UN COMPANY NAME                  DATE OF "
		#define STR0012 "                                                                     REQUIRED                     COSTO            FRMS.C.                 OF PURCHS       OF S.C. N.COT. SUPPL.                                  ISSUE   "
		#define STR0013 "Selecting Records..."
		#define STR0014 "CANCELLED BY THE OPERATOR"
		#define STR0015 "Total  -  "
		#define STR0016 "Orders generated by quotation Number"
		#define STR0017 "NUMBER ITEM PRODUCT         D E S C R I P T.               TP GRP    QUANTITY   UM               CENTER ISSUE      DELIV.     PETITIONER   DEADLINE          BLNCE        CODE   UN COMPANY NAME                        "
		#define STR0018 "                                                                     REQUIRED                     COST             OF S.C.                 OF PURCHS       OF S.C.        SUPPL.                                        "
		#define STR0019 "Limit Dt."
		#define STR0020 "PR Balance"
		#define STR0021 "CANCELLED BY THE SYSTEM"
		#define STR0022 "Purchase requests      "
		#define STR0023 "of Purchase"
		#define STR0024 "Number"
		#define STR0025 "PR"
		#define STR0026 "Item"
		#define STR0027 "Tp"
		#define STR0028 "MU"
		#define STR0029 "Date from"
		#define STR0030 "Issue"
		#define STR0031 "Delivery "
		#define STR0032 "Number"
		#define STR0033 "PO"
		#define STR0034 "Suppl."
		#define STR0035 "St"
	#else
		#define STR0001 If( cPaisLoc $ "ANG|PTG", "Emite uma relação para controle das solicitações registadas ,", "Emite uma relacao para controle das solicitacoes cadastradas ," )
		#define STR0002 If( cPaisLoc $ "ANG|PTG", "Seus respectivos pedidos e prazos de entrega.", "seus respectivos pedidos e prazos de entrega." )
		#define STR0003 If( cPaisLoc $ "ANG|PTG", " por solicitação    ", " Por Solicitacao    " )
		#define STR0004 If( cPaisLoc $ "ANG|PTG", " por produto        ", " Por Produto        " )
		#define STR0005 If( cPaisLoc $ "ANG|PTG", "Relação De Solicitações De Compras", "Relacao de Solicitacoes de Compras" )
		#define STR0006 If( cPaisLoc $ "ANG|PTG", "Código de barras", "Zebrado" )
		#define STR0007 If( cPaisLoc $ "ANG|PTG", "Administração", "Administracao" )
		#define STR0008 If( cPaisLoc $ "ANG|PTG", "Registo(s)", "REGISTRO(S)" )
		#define STR0009 If( cPaisLoc $ "ANG|PTG", "Relação De Solicitações De Compras", "RELACAO DE SOLICITACOES DE COMPRAS" )
		#define STR0010 If( cPaisLoc $ "ANG|PTG", " (incluindo Pedidos De Compra)", " (Incluindo Pedidos de Compra)" )
		#define STR0011 If( cPaisLoc $ "ANG|PTG", "Número item produto         d e s c r i ç ã  o              tp grup   quantidade um               centro emissão    entrega    solicitante  dt.limite         saldo n.ped/ código lj razão social                  data de ", "NUMERO ITEM PRODUTO         D E S C R I C A O              TP GRUP   QUANTIDADE UM               CENTRO EMISSAO    ENTREGA    SOLICITANTE  DT.LIMITE         SALDO N.PED/ CODIGO LJ RAZAO SOCIAL                  DATA DE " )
		#define STR0012 If( cPaisLoc $ "ANG|PTG", "                                                                     solicitada                   custo            da s.c.                 de compra       da s.c. n.ºcot. fornec                                  emissão ", "                                                                     SOLICITADA                   CUSTO            DA S.C.                 DE COMPRA       DA S.C. N.COT. FORNEC                                  EMISSAO " )
		#define STR0013 If( cPaisLoc $ "ANG|PTG", "A Seleccionar Registos...", "Selecionando Registros..." )
		#define STR0014 If( cPaisLoc $ "ANG|PTG", "Cancelado Pelo Operador", "CANCELADO PELO OPERADOR" )
		#define STR0015 "Total  -  "
		#define STR0016 If( cPaisLoc $ "ANG|PTG", "Pedidos Criados Por Cotação N.º", "Pedidos gerados por cotacao Num." )
		#define STR0017 If( cPaisLoc $ "ANG|PTG", "Número item produto         d e s c r i ç ã o              tp grup   quantidade um               centro emissão    entrega    solicitante  dt.limite         saldo        código lj razão social                        ", "NUMERO ITEM PRODUTO         D E S C R I C A O              TP GRUP   QUANTIDADE UM               CENTRO EMISSAO    ENTREGA    SOLICITANTE  DT.LIMITE         SALDO        CODIGO LJ RAZAO SOCIAL                        " )
		#define STR0018 If( cPaisLoc $ "ANG|PTG", "                                                                     solicitada                   custo            da s.c.                 de compra       da s.c.        fornec                                        ", "                                                                     SOLICITADA                   CUSTO            DA S.C.                 DE COMPRA       DA S.C.        FORNEC                                        " )
		#define STR0019 "Dt.Limite"
		#define STR0020 "Saldo SC"
		#define STR0021 If( cPaisLoc $ "ANG|PTG", "Cancelada Pelo Sistema.", "CANCELADA PELO SISTEMA." )
		#define STR0022 If( cPaisLoc $ "ANG|PTG", "Solicitações De Compras", "Solicitações de Compras" )
		#define STR0023 "de Compra"
		#define STR0024 If( cPaisLoc $ "ANG|PTG", "Número", "Numero" )
		#define STR0025 "SC"
		#define STR0026 If( cPaisLoc $ "ANG|PTG", "Elem", "Item" )
		#define STR0027 "Tp"
		#define STR0028 "UM"
		#define STR0029 "Data de"
		#define STR0030 If( cPaisLoc $ "ANG|PTG", "Emissão", "Emissao" )
		#define STR0031 "Entrega"
		#define STR0032 If( cPaisLoc $ "ANG|PTG", "Número", "Numero" )
		#define STR0033 "PC"
		#define STR0034 "Fornec."
		#define STR0035 "Lj"
	#endif
#endif
